// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "compute_layer_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic compute_layer_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic compute_layer_0_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> compute_layer_0_0::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<3> compute_layer_0_0::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<3> compute_layer_0_0::ap_ST_fsm_pp0_stage2 = "100";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> compute_layer_0_0::ap_const_lv1_1 = "1";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_2 = "10";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_1 = "1";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFE92 = "1111111111111111111010010010";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFE4A = "1111111111111111111001001010";
const sc_lv<26> compute_layer_0_0::ap_const_lv26_3FFFF97 = "11111111111111111110010111";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFE73 = "1111111111111111111001110011";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFED4 = "1111111111111111111011010100";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFEB6 = "1111111111111111111010110110";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFEB3 = "1111111111111111111010110011";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_7FFFF5C = "111111111111111111101011100";
const sc_lv<28> compute_layer_0_0::ap_const_lv28_FFFFE87 = "1111111111111111111010000111";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_F2 = "11110010";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_7FFFF0B = "111111111111111111100001011";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_7FFFF4B = "111111111111111111101001011";
const sc_lv<26> compute_layer_0_0::ap_const_lv26_5C = "1011100";
const sc_lv<26> compute_layer_0_0::ap_const_lv26_4A = "1001010";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_7FFFF52 = "111111111111111111101010010";
const sc_lv<25> compute_layer_0_0::ap_const_lv25_32 = "110010";
const sc_lv<24> compute_layer_0_0::ap_const_lv24_1D = "11101";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_BF = "10111111";
const sc_lv<24> compute_layer_0_0::ap_const_lv24_19 = "11001";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_9F = "10011111";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_7FFFF71 = "111111111111111111101110001";
const sc_lv<26> compute_layer_0_0::ap_const_lv26_3FFFF9F = "11111111111111111110011111";
const sc_lv<27> compute_layer_0_0::ap_const_lv27_7FFFF46 = "111111111111111111101000110";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_A = "1010";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_1A = "11010";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_1B = "11011";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_19 = "11001";
const sc_lv<6> compute_layer_0_0::ap_const_lv6_0 = "000000";
const sc_lv<2> compute_layer_0_0::ap_const_lv2_0 = "00";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_18 = "11000";
const sc_lv<9> compute_layer_0_0::ap_const_lv9_0 = "000000000";
const sc_lv<1> compute_layer_0_0::ap_const_lv1_0 = "0";
const sc_lv<7> compute_layer_0_0::ap_const_lv7_0 = "0000000";
const sc_lv<5> compute_layer_0_0::ap_const_lv5_0 = "00000";
const sc_lv<21> compute_layer_0_0::ap_const_lv21_0 = "000000000000000000000";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_14 = "10100";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_3 = "11";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_11 = "10001";
const sc_lv<3> compute_layer_0_0::ap_const_lv3_0 = "000";
const sc_lv<22> compute_layer_0_0::ap_const_lv22_0 = "0000000000000000000000";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_15 = "10101";
const sc_lv<32> compute_layer_0_0::ap_const_lv32_17 = "10111";
const sc_lv<16> compute_layer_0_0::ap_const_lv16_FF86 = "1111111110000110";

compute_layer_0_0::compute_layer_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_mul_18sjbC_x_U86 = new myproject_mul_18sjbC<1,3,18,10,28>("myproject_mul_18sjbC_x_U86");
    myproject_mul_18sjbC_x_U86->clk(ap_clk);
    myproject_mul_18sjbC_x_U86->reset(ap_rst);
    myproject_mul_18sjbC_x_U86->din0(grp_fu_402_p0);
    myproject_mul_18sjbC_x_U86->din1(grp_fu_402_p1);
    myproject_mul_18sjbC_x_U86->ce(ap_var_for_const0);
    myproject_mul_18sjbC_x_U86->dout(grp_fu_402_p2);
    myproject_mul_18sjbC_x_U87 = new myproject_mul_18sjbC<1,3,18,10,28>("myproject_mul_18sjbC_x_U87");
    myproject_mul_18sjbC_x_U87->clk(ap_clk);
    myproject_mul_18sjbC_x_U87->reset(ap_rst);
    myproject_mul_18sjbC_x_U87->din0(grp_fu_403_p0);
    myproject_mul_18sjbC_x_U87->din1(grp_fu_403_p1);
    myproject_mul_18sjbC_x_U87->ce(ap_var_for_const0);
    myproject_mul_18sjbC_x_U87->dout(grp_fu_403_p2);
    myproject_mul_18sjbC_x_U88 = new myproject_mul_18sjbC<1,3,18,10,28>("myproject_mul_18sjbC_x_U88");
    myproject_mul_18sjbC_x_U88->clk(ap_clk);
    myproject_mul_18sjbC_x_U88->reset(ap_rst);
    myproject_mul_18sjbC_x_U88->din0(grp_fu_404_p0);
    myproject_mul_18sjbC_x_U88->din1(grp_fu_404_p1);
    myproject_mul_18sjbC_x_U88->ce(ap_var_for_const0);
    myproject_mul_18sjbC_x_U88->dout(grp_fu_404_p2);
    myproject_mul_18sfYi_x_U89 = new myproject_mul_18sfYi<1,3,18,10,27>("myproject_mul_18sfYi_x_U89");
    myproject_mul_18sfYi_x_U89->clk(ap_clk);
    myproject_mul_18sfYi_x_U89->reset(ap_rst);
    myproject_mul_18sfYi_x_U89->din0(grp_fu_405_p0);
    myproject_mul_18sfYi_x_U89->din1(grp_fu_405_p1);
    myproject_mul_18sfYi_x_U89->ce(ap_var_for_const0);
    myproject_mul_18sfYi_x_U89->dout(grp_fu_405_p2);
    myproject_mul_18seOg_x_U90 = new myproject_mul_18seOg<1,3,18,9,27>("myproject_mul_18seOg_x_U90");
    myproject_mul_18seOg_x_U90->clk(ap_clk);
    myproject_mul_18seOg_x_U90->reset(ap_rst);
    myproject_mul_18seOg_x_U90->din0(grp_fu_406_p0);
    myproject_mul_18seOg_x_U90->din1(grp_fu_406_p1);
    myproject_mul_18seOg_x_U90->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U90->dout(grp_fu_406_p2);
    myproject_mul_18seOg_x_U91 = new myproject_mul_18seOg<1,3,18,9,27>("myproject_mul_18seOg_x_U91");
    myproject_mul_18seOg_x_U91->clk(ap_clk);
    myproject_mul_18seOg_x_U91->reset(ap_rst);
    myproject_mul_18seOg_x_U91->din0(grp_fu_407_p0);
    myproject_mul_18seOg_x_U91->din1(grp_fu_407_p1);
    myproject_mul_18seOg_x_U91->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U91->dout(grp_fu_407_p2);
    myproject_mul_18sg8j_x_U92 = new myproject_mul_18sg8j<1,3,18,9,27>("myproject_mul_18sg8j_x_U92");
    myproject_mul_18sg8j_x_U92->clk(ap_clk);
    myproject_mul_18sg8j_x_U92->reset(ap_rst);
    myproject_mul_18sg8j_x_U92->din0(grp_fu_408_p0);
    myproject_mul_18sg8j_x_U92->din1(grp_fu_408_p1);
    myproject_mul_18sg8j_x_U92->ce(ap_var_for_const0);
    myproject_mul_18sg8j_x_U92->dout(grp_fu_408_p2);
    myproject_mul_18seOg_x_U93 = new myproject_mul_18seOg<1,3,18,9,27>("myproject_mul_18seOg_x_U93");
    myproject_mul_18seOg_x_U93->clk(ap_clk);
    myproject_mul_18seOg_x_U93->reset(ap_rst);
    myproject_mul_18seOg_x_U93->din0(grp_fu_409_p0);
    myproject_mul_18seOg_x_U93->din1(grp_fu_409_p1);
    myproject_mul_18seOg_x_U93->ce(ap_var_for_const0);
    myproject_mul_18seOg_x_U93->dout(grp_fu_409_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_10_cast_fu_1261_p1);
    sensitive << ( ap_port_reg_data_11_V_read );

    SC_METHOD(thread_OP1_V_11_cast_fu_1036_p1);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_OP1_V_12_cast_fu_1293_p1);
    sensitive << ( ap_port_reg_data_13_V_read );

    SC_METHOD(thread_OP1_V_13_cast_fu_1041_p1);
    sensitive << ( ap_port_reg_data_14_V_read );

    SC_METHOD(thread_OP1_V_14_cast_fu_1046_p1);
    sensitive << ( ap_port_reg_data_15_V_read );

    SC_METHOD(thread_OP1_V_16_cast_fu_1051_p1);
    sensitive << ( ap_port_reg_data_17_V_read );

    SC_METHOD(thread_OP1_V_17_cast_fu_1056_p1);
    sensitive << ( ap_port_reg_data_18_V_read );

    SC_METHOD(thread_OP1_V_19_cast_fu_1061_p1);
    sensitive << ( ap_port_reg_data_20_V_read );

    SC_METHOD(thread_OP1_V_1_cast_fu_1001_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_OP1_V_20_cast_fu_1066_p1);
    sensitive << ( ap_port_reg_data_21_V_read );

    SC_METHOD(thread_OP1_V_21_cast_fu_1071_p1);
    sensitive << ( ap_port_reg_data_22_V_read );

    SC_METHOD(thread_OP1_V_22_cast_fu_1076_p1);
    sensitive << ( ap_port_reg_data_23_V_read );

    SC_METHOD(thread_OP1_V_23_cast_fu_1369_p1);
    sensitive << ( ap_port_reg_data_24_V_read );

    SC_METHOD(thread_OP1_V_24_cast_fu_1374_p1);
    sensitive << ( ap_port_reg_data_25_V_read );

    SC_METHOD(thread_OP1_V_25_cast_fu_1379_p1);
    sensitive << ( ap_port_reg_data_26_V_read );

    SC_METHOD(thread_OP1_V_26_cast_fu_1384_p1);
    sensitive << ( ap_port_reg_data_27_V_read );

    SC_METHOD(thread_OP1_V_28_cast_fu_1429_p1);
    sensitive << ( ap_port_reg_data_29_V_read );

    SC_METHOD(thread_OP1_V_29_cast_fu_1434_p1);
    sensitive << ( ap_port_reg_data_30_V_read );

    SC_METHOD(thread_OP1_V_30_cast_fu_1439_p1);
    sensitive << ( ap_port_reg_data_31_V_read );

    SC_METHOD(thread_OP1_V_3_cast_fu_1006_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_OP1_V_5_cast_fu_1011_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_OP1_V_7_cast_fu_1016_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_OP1_V_8_cast_fu_1021_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_OP1_V_9_cast_fu_1026_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_OP1_V_cast_fu_1031_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_preg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_pipeline_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_pipeline_start_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp30_fu_1764_p2 );
    sensitive << ( tmp15_fu_1756_p2 );

    SC_METHOD(thread_grp_fu_402_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_7_cast_fu_1016_p1 );
    sensitive << ( OP1_V_17_cast_fu_1056_p1 );
    sensitive << ( OP1_V_28_cast_fu_1429_p1 );

    SC_METHOD(thread_grp_fu_402_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_403_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_11_cast_fu_1036_p1 );
    sensitive << ( OP1_V_22_cast_fu_1076_p1 );
    sensitive << ( OP1_V_23_cast_fu_1369_p1 );

    SC_METHOD(thread_grp_fu_403_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_404_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_9_cast_fu_1026_p1 );
    sensitive << ( OP1_V_13_cast_fu_1041_p1 );
    sensitive << ( OP1_V_24_cast_fu_1374_p1 );

    SC_METHOD(thread_grp_fu_404_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_405_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_cast_fu_1031_p1 );
    sensitive << ( OP1_V_21_cast_fu_1071_p1 );

    SC_METHOD(thread_grp_fu_405_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_406_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_3_cast_fu_1006_p1 );
    sensitive << ( OP1_V_14_cast_fu_1046_p1 );
    sensitive << ( OP1_V_25_cast_fu_1379_p1 );

    SC_METHOD(thread_grp_fu_406_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_407_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_8_cast_fu_1021_p1 );
    sensitive << ( OP1_V_19_cast_fu_1061_p1 );
    sensitive << ( OP1_V_30_cast_fu_1439_p1 );

    SC_METHOD(thread_grp_fu_407_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_408_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_5_cast_fu_1011_p1 );
    sensitive << ( OP1_V_16_cast_fu_1051_p1 );
    sensitive << ( OP1_V_26_cast_fu_1384_p1 );

    SC_METHOD(thread_grp_fu_408_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_409_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( OP1_V_1_cast_fu_1001_p1 );
    sensitive << ( OP1_V_20_cast_fu_1066_p1 );
    sensitive << ( OP1_V_29_cast_fu_1434_p1 );

    SC_METHOD(thread_grp_fu_409_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );

    SC_METHOD(thread_grp_fu_963_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( grp_fu_406_p2 );

    SC_METHOD(thread_p_Val2_1_10_fu_1277_p2);
    sensitive << ( p_shl4_cast_fu_1273_p1 );
    sensitive << ( OP1_V_10_cast_fu_1261_p1 );

    SC_METHOD(thread_p_Val2_1_12_fu_1315_p2);
    sensitive << ( p_neg_fu_1309_p2 );
    sensitive << ( OP1_V_12_cast_fu_1293_p1 );

    SC_METHOD(thread_p_Val2_1_17_fu_1353_p2);
    sensitive << ( p_shl2_cast_fu_1349_p1 );

    SC_METHOD(thread_p_Val2_1_26_fu_1413_p2);
    sensitive << ( p_shl_cast_fu_1397_p1 );
    sensitive << ( p_shl1_cast_fu_1409_p1 );

    SC_METHOD(thread_p_Val2_1_2_fu_1145_p2);
    sensitive << ( p_shl11_cast_fu_1141_p1 );
    sensitive << ( p_shl9_cast_fu_1129_p1 );

    SC_METHOD(thread_p_Val2_1_4_fu_1195_p2);
    sensitive << ( p_shl7_cast_fu_1179_p1 );
    sensitive << ( p_shl8_cast_fu_1191_p1 );

    SC_METHOD(thread_p_Val2_1_6_fu_1235_p2);
    sensitive << ( p_shl5_cast_fu_1219_p1 );
    sensitive << ( p_shl6_cast_fu_1231_p1 );

    SC_METHOD(thread_p_Val2_1_fu_1105_p2);
    sensitive << ( p_shl14_cast_fu_1101_p1 );
    sensitive << ( p_shl12_cast_fu_1089_p1 );

    SC_METHOD(thread_p_neg_fu_1309_p2);
    sensitive << ( p_shl3_cast_fu_1305_p1 );

    SC_METHOD(thread_p_shl10_fu_1081_p3);
    sensitive << ( ap_port_reg_data_0_V_read );

    SC_METHOD(thread_p_shl11_cast_fu_1141_p1);
    sensitive << ( p_shl11_fu_1133_p3 );

    SC_METHOD(thread_p_shl11_fu_1133_p3);
    sensitive << ( ap_port_reg_data_2_V_read );

    SC_METHOD(thread_p_shl12_cast_fu_1089_p1);
    sensitive << ( p_shl10_fu_1081_p3 );

    SC_METHOD(thread_p_shl12_fu_1093_p3);
    sensitive << ( ap_port_reg_data_0_V_read );

    SC_METHOD(thread_p_shl14_cast_fu_1101_p1);
    sensitive << ( p_shl12_fu_1093_p3 );

    SC_METHOD(thread_p_shl1_cast_fu_1409_p1);
    sensitive << ( p_shl1_fu_1401_p3 );

    SC_METHOD(thread_p_shl1_fu_1401_p3);
    sensitive << ( ap_port_reg_data_28_V_read );

    SC_METHOD(thread_p_shl2_cast_fu_1349_p1);
    sensitive << ( p_shl2_fu_1341_p3 );

    SC_METHOD(thread_p_shl2_fu_1341_p3);
    sensitive << ( ap_port_reg_data_19_V_read );

    SC_METHOD(thread_p_shl3_cast_fu_1305_p1);
    sensitive << ( p_shl3_fu_1297_p3 );

    SC_METHOD(thread_p_shl3_fu_1297_p3);
    sensitive << ( ap_port_reg_data_13_V_read );

    SC_METHOD(thread_p_shl4_cast_fu_1273_p1);
    sensitive << ( p_shl4_fu_1265_p3 );

    SC_METHOD(thread_p_shl4_fu_1265_p3);
    sensitive << ( ap_port_reg_data_11_V_read );

    SC_METHOD(thread_p_shl5_cast_fu_1219_p1);
    sensitive << ( p_shl5_fu_1211_p3 );

    SC_METHOD(thread_p_shl5_fu_1211_p3);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_p_shl6_cast_fu_1231_p1);
    sensitive << ( p_shl6_fu_1223_p3 );

    SC_METHOD(thread_p_shl6_fu_1223_p3);
    sensitive << ( ap_port_reg_data_6_V_read );

    SC_METHOD(thread_p_shl7_cast_fu_1179_p1);
    sensitive << ( p_shl7_fu_1171_p3 );

    SC_METHOD(thread_p_shl7_fu_1171_p3);
    sensitive << ( ap_port_reg_data_4_V_read );

    SC_METHOD(thread_p_shl8_cast_fu_1191_p1);
    sensitive << ( p_shl8_fu_1183_p3 );

    SC_METHOD(thread_p_shl8_fu_1183_p3);
    sensitive << ( ap_port_reg_data_4_V_read );

    SC_METHOD(thread_p_shl9_cast_fu_1129_p1);
    sensitive << ( p_shl9_fu_1121_p3 );

    SC_METHOD(thread_p_shl9_fu_1121_p3);
    sensitive << ( ap_port_reg_data_2_V_read );

    SC_METHOD(thread_p_shl_cast_fu_1397_p1);
    sensitive << ( p_shl_fu_1389_p3 );

    SC_METHOD(thread_p_shl_fu_1389_p3);
    sensitive << ( ap_port_reg_data_28_V_read );

    SC_METHOD(thread_tmp15_fu_1756_p2);
    sensitive << ( tmp16_reg_1965 );
    sensitive << ( tmp23_reg_1990 );

    SC_METHOD(thread_tmp16_fu_1556_p2);
    sensitive << ( tmp20_fu_1550_p2 );
    sensitive << ( tmp17_fu_1532_p2 );

    SC_METHOD(thread_tmp17_fu_1532_p2);
    sensitive << ( tmp19_fu_1527_p2 );
    sensitive << ( tmp18_fu_1521_p2 );

    SC_METHOD(thread_tmp18_fu_1521_p2);
    sensitive << ( tmp_6_fu_1444_p1 );
    sensitive << ( tmp_9_fu_1447_p1 );

    SC_METHOD(thread_tmp19_fu_1527_p2);
    sensitive << ( tmp_10_2_reg_1860 );
    sensitive << ( tmp_12_fu_1451_p1 );

    SC_METHOD(thread_tmp20_fu_1550_p2);
    sensitive << ( tmp22_fu_1544_p2 );
    sensitive << ( tmp21_fu_1538_p2 );

    SC_METHOD(thread_tmp21_fu_1538_p2);
    sensitive << ( tmp_15_fu_1454_p1 );
    sensitive << ( tmp_18_fu_1457_p1 );

    SC_METHOD(thread_tmp22_fu_1544_p2);
    sensitive << ( reg_981 );
    sensitive << ( tmp_21_fu_1461_p1 );

    SC_METHOD(thread_tmp23_fu_1642_p2);
    sensitive << ( tmp27_fu_1636_p2 );
    sensitive << ( tmp24_fu_1620_p2 );

    SC_METHOD(thread_tmp24_fu_1620_p2);
    sensitive << ( tmp25_reg_1970 );
    sensitive << ( tmp26_reg_1975 );

    SC_METHOD(thread_tmp25_fu_1562_p2);
    sensitive << ( reg_985 );
    sensitive << ( tmp_24_fu_1464_p1 );

    SC_METHOD(thread_tmp26_fu_1568_p2);
    sensitive << ( tmp_27_fu_1467_p1 );
    sensitive << ( tmp_30_fu_1471_p1 );

    SC_METHOD(thread_tmp27_fu_1636_p2);
    sensitive << ( tmp29_fu_1630_p2 );
    sensitive << ( tmp28_fu_1624_p2 );

    SC_METHOD(thread_tmp28_fu_1624_p2);
    sensitive << ( reg_993 );
    sensitive << ( tmp_33_fu_1580_p1 );

    SC_METHOD(thread_tmp29_fu_1630_p2);
    sensitive << ( tmp_36_fu_1583_p1 );
    sensitive << ( tmp_39_fu_1586_p1 );

    SC_METHOD(thread_tmp30_fu_1764_p2);
    sensitive << ( tmp38_reg_2010 );
    sensitive << ( tmp31_fu_1760_p2 );

    SC_METHOD(thread_tmp31_fu_1760_p2);
    sensitive << ( tmp32_reg_1995 );
    sensitive << ( tmp35_reg_2005 );

    SC_METHOD(thread_tmp32_fu_1657_p2);
    sensitive << ( tmp34_cast_fu_1654_p1 );
    sensitive << ( tmp33_fu_1648_p2 );

    SC_METHOD(thread_tmp33_fu_1648_p2);
    sensitive << ( reg_981 );
    sensitive << ( tmp_44_fu_1593_p1 );

    SC_METHOD(thread_tmp34_cast_fu_1654_p1);
    sensitive << ( tmp34_reg_1980 );

    SC_METHOD(thread_tmp34_fu_1574_p2);
    sensitive << ( tmp_47_cast_fu_1494_p1 );
    sensitive << ( tmp_50_cast_fu_1507_p1 );

    SC_METHOD(thread_tmp35_fu_1711_p2);
    sensitive << ( tmp37_fu_1706_p2 );
    sensitive << ( tmp36_fu_1700_p2 );

    SC_METHOD(thread_tmp36_fu_1700_p2);
    sensitive << ( tmp_53_fu_1675_p1 );
    sensitive << ( tmp_56_fu_1678_p1 );

    SC_METHOD(thread_tmp37_fu_1706_p2);
    sensitive << ( reg_993 );
    sensitive << ( tmp_10_3_reg_1960 );

    SC_METHOD(thread_tmp38_fu_1750_p2);
    sensitive << ( tmp42_fu_1744_p2 );
    sensitive << ( tmp39_fu_1729_p2 );

    SC_METHOD(thread_tmp39_fu_1729_p2);
    sensitive << ( tmp41_fu_1723_p2 );
    sensitive << ( tmp40_fu_1717_p2 );

    SC_METHOD(thread_tmp40_fu_1717_p2);
    sensitive << ( reg_985 );
    sensitive << ( tmp_58_fu_1682_p1 );

    SC_METHOD(thread_tmp41_fu_1723_p2);
    sensitive << ( tmp_60_fu_1686_p1 );
    sensitive << ( tmp_62_fu_1690_p1 );

    SC_METHOD(thread_tmp42_fu_1744_p2);
    sensitive << ( tmp44_cast_fu_1741_p1 );
    sensitive << ( tmp43_fu_1735_p2 );

    SC_METHOD(thread_tmp43_fu_1735_p2);
    sensitive << ( tmp_64_fu_1693_p1 );
    sensitive << ( tmp_66_fu_1696_p1 );

    SC_METHOD(thread_tmp44_cast_fu_1741_p1);
    sensitive << ( tmp44_reg_2000 );

    SC_METHOD(thread_tmp44_fu_1669_p2);
    sensitive << ( tmp45_fu_1663_p2 );
    sensitive << ( tmp_72_cast_fu_1616_p1 );

    SC_METHOD(thread_tmp45_fu_1663_p2);
    sensitive << ( tmp_10_15_cast_fu_1590_p1 );

    SC_METHOD(thread_tmp_10_15_cast_fu_1590_p1);
    sensitive << ( tmp_41_reg_1895 );

    SC_METHOD(thread_tmp_12_fu_1451_p1);
    sensitive << ( tmp_11_reg_1865 );

    SC_METHOD(thread_tmp_15_fu_1454_p1);
    sensitive << ( tmp_14_reg_1870 );

    SC_METHOD(thread_tmp_183_fu_1497_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_fu_407_p2 );

    SC_METHOD(thread_tmp_183_fu_1497_p4);
    sensitive << ( tmp_183_fu_1497_p1 );

    SC_METHOD(thread_tmp_184_fu_1606_p1);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( grp_fu_407_p2 );

    SC_METHOD(thread_tmp_184_fu_1606_p4);
    sensitive << ( tmp_184_fu_1606_p1 );

    SC_METHOD(thread_tmp_18_fu_1457_p1);
    sensitive << ( reg_977 );

    SC_METHOD(thread_tmp_21_fu_1461_p1);
    sensitive << ( tmp_20_reg_1875 );

    SC_METHOD(thread_tmp_24_fu_1464_p1);
    sensitive << ( tmp_23_reg_1880 );

    SC_METHOD(thread_tmp_27_fu_1467_p1);
    sensitive << ( reg_989 );

    SC_METHOD(thread_tmp_30_fu_1471_p1);
    sensitive << ( tmp_29_reg_1885 );

    SC_METHOD(thread_tmp_33_fu_1580_p1);
    sensitive << ( tmp_32_reg_1890 );

    SC_METHOD(thread_tmp_35_fu_1474_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_fu_404_p2 );

    SC_METHOD(thread_tmp_36_fu_1583_p1);
    sensitive << ( tmp_35_reg_1945 );

    SC_METHOD(thread_tmp_39_fu_1586_p1);
    sensitive << ( reg_997 );

    SC_METHOD(thread_tmp_43_fu_1484_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_fu_408_p2 );

    SC_METHOD(thread_tmp_44_fu_1593_p1);
    sensitive << ( tmp_43_reg_1950 );

    SC_METHOD(thread_tmp_47_cast_fu_1494_p1);
    sensitive << ( tmp_182_reg_1900 );

    SC_METHOD(thread_tmp_50_cast_fu_1507_p1);
    sensitive << ( tmp_183_fu_1497_p4 );

    SC_METHOD(thread_tmp_52_fu_1511_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_fu_409_p2 );

    SC_METHOD(thread_tmp_53_fu_1675_p1);
    sensitive << ( tmp_52_reg_1955 );

    SC_METHOD(thread_tmp_56_fu_1678_p1);
    sensitive << ( reg_989 );

    SC_METHOD(thread_tmp_58_fu_1682_p1);
    sensitive << ( reg_997 );

    SC_METHOD(thread_tmp_60_fu_1686_p1);
    sensitive << ( reg_977 );

    SC_METHOD(thread_tmp_62_fu_1690_p1);
    sensitive << ( tmp_61_reg_1925 );

    SC_METHOD(thread_tmp_63_fu_1596_p1);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( grp_fu_402_p2 );

    SC_METHOD(thread_tmp_64_fu_1693_p1);
    sensitive << ( tmp_63_reg_1985 );

    SC_METHOD(thread_tmp_66_fu_1696_p1);
    sensitive << ( reg_973 );

    SC_METHOD(thread_tmp_6_fu_1444_p1);
    sensitive << ( tmp_5_reg_1855 );

    SC_METHOD(thread_tmp_72_cast_fu_1616_p1);
    sensitive << ( tmp_184_fu_1606_p4 );

    SC_METHOD(thread_tmp_9_fu_1447_p1);
    sensitive << ( reg_973 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_pipeline_idle_pp0 );
    sensitive << ( ap_pipeline_start_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_preg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "compute_layer_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, reg_973, "reg_973");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, reg_977, "reg_977");
    sc_trace(mVcdFile, reg_981, "reg_981");
    sc_trace(mVcdFile, reg_985, "reg_985");
    sc_trace(mVcdFile, reg_989, "reg_989");
    sc_trace(mVcdFile, reg_993, "reg_993");
    sc_trace(mVcdFile, reg_997, "reg_997");
    sc_trace(mVcdFile, OP1_V_1_cast_fu_1001_p1, "OP1_V_1_cast_fu_1001_p1");
    sc_trace(mVcdFile, OP1_V_3_cast_fu_1006_p1, "OP1_V_3_cast_fu_1006_p1");
    sc_trace(mVcdFile, OP1_V_5_cast_fu_1011_p1, "OP1_V_5_cast_fu_1011_p1");
    sc_trace(mVcdFile, OP1_V_7_cast_fu_1016_p1, "OP1_V_7_cast_fu_1016_p1");
    sc_trace(mVcdFile, OP1_V_8_cast_fu_1021_p1, "OP1_V_8_cast_fu_1021_p1");
    sc_trace(mVcdFile, OP1_V_9_cast_fu_1026_p1, "OP1_V_9_cast_fu_1026_p1");
    sc_trace(mVcdFile, OP1_V_cast_fu_1031_p1, "OP1_V_cast_fu_1031_p1");
    sc_trace(mVcdFile, OP1_V_11_cast_fu_1036_p1, "OP1_V_11_cast_fu_1036_p1");
    sc_trace(mVcdFile, OP1_V_13_cast_fu_1041_p1, "OP1_V_13_cast_fu_1041_p1");
    sc_trace(mVcdFile, OP1_V_14_cast_fu_1046_p1, "OP1_V_14_cast_fu_1046_p1");
    sc_trace(mVcdFile, OP1_V_16_cast_fu_1051_p1, "OP1_V_16_cast_fu_1051_p1");
    sc_trace(mVcdFile, OP1_V_17_cast_fu_1056_p1, "OP1_V_17_cast_fu_1056_p1");
    sc_trace(mVcdFile, OP1_V_19_cast_fu_1061_p1, "OP1_V_19_cast_fu_1061_p1");
    sc_trace(mVcdFile, OP1_V_20_cast_fu_1066_p1, "OP1_V_20_cast_fu_1066_p1");
    sc_trace(mVcdFile, OP1_V_21_cast_fu_1071_p1, "OP1_V_21_cast_fu_1071_p1");
    sc_trace(mVcdFile, OP1_V_22_cast_fu_1076_p1, "OP1_V_22_cast_fu_1076_p1");
    sc_trace(mVcdFile, tmp_5_reg_1855, "tmp_5_reg_1855");
    sc_trace(mVcdFile, tmp_10_2_reg_1860, "tmp_10_2_reg_1860");
    sc_trace(mVcdFile, tmp_11_reg_1865, "tmp_11_reg_1865");
    sc_trace(mVcdFile, tmp_14_reg_1870, "tmp_14_reg_1870");
    sc_trace(mVcdFile, tmp_20_reg_1875, "tmp_20_reg_1875");
    sc_trace(mVcdFile, tmp_23_reg_1880, "tmp_23_reg_1880");
    sc_trace(mVcdFile, tmp_29_reg_1885, "tmp_29_reg_1885");
    sc_trace(mVcdFile, tmp_32_reg_1890, "tmp_32_reg_1890");
    sc_trace(mVcdFile, tmp_41_reg_1895, "tmp_41_reg_1895");
    sc_trace(mVcdFile, tmp_182_reg_1900, "tmp_182_reg_1900");
    sc_trace(mVcdFile, OP1_V_23_cast_fu_1369_p1, "OP1_V_23_cast_fu_1369_p1");
    sc_trace(mVcdFile, OP1_V_24_cast_fu_1374_p1, "OP1_V_24_cast_fu_1374_p1");
    sc_trace(mVcdFile, OP1_V_25_cast_fu_1379_p1, "OP1_V_25_cast_fu_1379_p1");
    sc_trace(mVcdFile, OP1_V_26_cast_fu_1384_p1, "OP1_V_26_cast_fu_1384_p1");
    sc_trace(mVcdFile, tmp_61_reg_1925, "tmp_61_reg_1925");
    sc_trace(mVcdFile, OP1_V_28_cast_fu_1429_p1, "OP1_V_28_cast_fu_1429_p1");
    sc_trace(mVcdFile, OP1_V_29_cast_fu_1434_p1, "OP1_V_29_cast_fu_1434_p1");
    sc_trace(mVcdFile, OP1_V_30_cast_fu_1439_p1, "OP1_V_30_cast_fu_1439_p1");
    sc_trace(mVcdFile, tmp_35_reg_1945, "tmp_35_reg_1945");
    sc_trace(mVcdFile, tmp_43_reg_1950, "tmp_43_reg_1950");
    sc_trace(mVcdFile, tmp_52_reg_1955, "tmp_52_reg_1955");
    sc_trace(mVcdFile, tmp_10_3_reg_1960, "tmp_10_3_reg_1960");
    sc_trace(mVcdFile, tmp16_fu_1556_p2, "tmp16_fu_1556_p2");
    sc_trace(mVcdFile, tmp16_reg_1965, "tmp16_reg_1965");
    sc_trace(mVcdFile, tmp25_fu_1562_p2, "tmp25_fu_1562_p2");
    sc_trace(mVcdFile, tmp25_reg_1970, "tmp25_reg_1970");
    sc_trace(mVcdFile, tmp26_fu_1568_p2, "tmp26_fu_1568_p2");
    sc_trace(mVcdFile, tmp26_reg_1975, "tmp26_reg_1975");
    sc_trace(mVcdFile, tmp34_fu_1574_p2, "tmp34_fu_1574_p2");
    sc_trace(mVcdFile, tmp34_reg_1980, "tmp34_reg_1980");
    sc_trace(mVcdFile, tmp_63_reg_1985, "tmp_63_reg_1985");
    sc_trace(mVcdFile, tmp23_fu_1642_p2, "tmp23_fu_1642_p2");
    sc_trace(mVcdFile, tmp23_reg_1990, "tmp23_reg_1990");
    sc_trace(mVcdFile, tmp32_fu_1657_p2, "tmp32_fu_1657_p2");
    sc_trace(mVcdFile, tmp32_reg_1995, "tmp32_reg_1995");
    sc_trace(mVcdFile, tmp44_fu_1669_p2, "tmp44_fu_1669_p2");
    sc_trace(mVcdFile, tmp44_reg_2000, "tmp44_reg_2000");
    sc_trace(mVcdFile, tmp35_fu_1711_p2, "tmp35_fu_1711_p2");
    sc_trace(mVcdFile, tmp35_reg_2005, "tmp35_reg_2005");
    sc_trace(mVcdFile, tmp38_fu_1750_p2, "tmp38_fu_1750_p2");
    sc_trace(mVcdFile, tmp38_reg_2010, "tmp38_reg_2010");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_preg, "ap_enable_reg_pp0_iter0_preg");
    sc_trace(mVcdFile, ap_port_reg_data_0_V_read, "ap_port_reg_data_0_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_2_V_read, "ap_port_reg_data_2_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_4_V_read, "ap_port_reg_data_4_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_6_V_read, "ap_port_reg_data_6_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_11_V_read, "ap_port_reg_data_11_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_13_V_read, "ap_port_reg_data_13_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_14_V_read, "ap_port_reg_data_14_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_15_V_read, "ap_port_reg_data_15_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_16_V_read, "ap_port_reg_data_16_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_17_V_read, "ap_port_reg_data_17_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_18_V_read, "ap_port_reg_data_18_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_19_V_read, "ap_port_reg_data_19_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_20_V_read, "ap_port_reg_data_20_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_21_V_read, "ap_port_reg_data_21_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_22_V_read, "ap_port_reg_data_22_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_23_V_read, "ap_port_reg_data_23_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_24_V_read, "ap_port_reg_data_24_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_25_V_read, "ap_port_reg_data_25_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_26_V_read, "ap_port_reg_data_26_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_27_V_read, "ap_port_reg_data_27_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_28_V_read, "ap_port_reg_data_28_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_29_V_read, "ap_port_reg_data_29_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_30_V_read, "ap_port_reg_data_30_V_read");
    sc_trace(mVcdFile, ap_port_reg_data_31_V_read, "ap_port_reg_data_31_V_read");
    sc_trace(mVcdFile, grp_fu_402_p0, "grp_fu_402_p0");
    sc_trace(mVcdFile, grp_fu_402_p1, "grp_fu_402_p1");
    sc_trace(mVcdFile, grp_fu_403_p0, "grp_fu_403_p0");
    sc_trace(mVcdFile, grp_fu_403_p1, "grp_fu_403_p1");
    sc_trace(mVcdFile, grp_fu_404_p0, "grp_fu_404_p0");
    sc_trace(mVcdFile, grp_fu_404_p1, "grp_fu_404_p1");
    sc_trace(mVcdFile, grp_fu_405_p0, "grp_fu_405_p0");
    sc_trace(mVcdFile, grp_fu_405_p1, "grp_fu_405_p1");
    sc_trace(mVcdFile, grp_fu_406_p0, "grp_fu_406_p0");
    sc_trace(mVcdFile, grp_fu_406_p1, "grp_fu_406_p1");
    sc_trace(mVcdFile, grp_fu_407_p0, "grp_fu_407_p0");
    sc_trace(mVcdFile, grp_fu_407_p1, "grp_fu_407_p1");
    sc_trace(mVcdFile, grp_fu_408_p0, "grp_fu_408_p0");
    sc_trace(mVcdFile, grp_fu_408_p1, "grp_fu_408_p1");
    sc_trace(mVcdFile, grp_fu_409_p0, "grp_fu_409_p0");
    sc_trace(mVcdFile, grp_fu_409_p1, "grp_fu_409_p1");
    sc_trace(mVcdFile, grp_fu_409_p2, "grp_fu_409_p2");
    sc_trace(mVcdFile, grp_fu_408_p2, "grp_fu_408_p2");
    sc_trace(mVcdFile, grp_fu_402_p2, "grp_fu_402_p2");
    sc_trace(mVcdFile, grp_fu_404_p2, "grp_fu_404_p2");
    sc_trace(mVcdFile, grp_fu_405_p2, "grp_fu_405_p2");
    sc_trace(mVcdFile, grp_fu_403_p2, "grp_fu_403_p2");
    sc_trace(mVcdFile, grp_fu_963_p1, "grp_fu_963_p1");
    sc_trace(mVcdFile, grp_fu_406_p2, "grp_fu_406_p2");
    sc_trace(mVcdFile, p_shl10_fu_1081_p3, "p_shl10_fu_1081_p3");
    sc_trace(mVcdFile, p_shl12_fu_1093_p3, "p_shl12_fu_1093_p3");
    sc_trace(mVcdFile, p_shl14_cast_fu_1101_p1, "p_shl14_cast_fu_1101_p1");
    sc_trace(mVcdFile, p_shl12_cast_fu_1089_p1, "p_shl12_cast_fu_1089_p1");
    sc_trace(mVcdFile, p_Val2_1_fu_1105_p2, "p_Val2_1_fu_1105_p2");
    sc_trace(mVcdFile, p_shl9_fu_1121_p3, "p_shl9_fu_1121_p3");
    sc_trace(mVcdFile, p_shl11_fu_1133_p3, "p_shl11_fu_1133_p3");
    sc_trace(mVcdFile, p_shl11_cast_fu_1141_p1, "p_shl11_cast_fu_1141_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_1129_p1, "p_shl9_cast_fu_1129_p1");
    sc_trace(mVcdFile, p_Val2_1_2_fu_1145_p2, "p_Val2_1_2_fu_1145_p2");
    sc_trace(mVcdFile, p_shl7_fu_1171_p3, "p_shl7_fu_1171_p3");
    sc_trace(mVcdFile, p_shl8_fu_1183_p3, "p_shl8_fu_1183_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_1179_p1, "p_shl7_cast_fu_1179_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_1191_p1, "p_shl8_cast_fu_1191_p1");
    sc_trace(mVcdFile, p_Val2_1_4_fu_1195_p2, "p_Val2_1_4_fu_1195_p2");
    sc_trace(mVcdFile, p_shl5_fu_1211_p3, "p_shl5_fu_1211_p3");
    sc_trace(mVcdFile, p_shl6_fu_1223_p3, "p_shl6_fu_1223_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_1219_p1, "p_shl5_cast_fu_1219_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_1231_p1, "p_shl6_cast_fu_1231_p1");
    sc_trace(mVcdFile, p_Val2_1_6_fu_1235_p2, "p_Val2_1_6_fu_1235_p2");
    sc_trace(mVcdFile, grp_fu_407_p2, "grp_fu_407_p2");
    sc_trace(mVcdFile, p_shl4_fu_1265_p3, "p_shl4_fu_1265_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_1273_p1, "p_shl4_cast_fu_1273_p1");
    sc_trace(mVcdFile, OP1_V_10_cast_fu_1261_p1, "OP1_V_10_cast_fu_1261_p1");
    sc_trace(mVcdFile, p_Val2_1_10_fu_1277_p2, "p_Val2_1_10_fu_1277_p2");
    sc_trace(mVcdFile, p_shl3_fu_1297_p3, "p_shl3_fu_1297_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_1305_p1, "p_shl3_cast_fu_1305_p1");
    sc_trace(mVcdFile, p_neg_fu_1309_p2, "p_neg_fu_1309_p2");
    sc_trace(mVcdFile, OP1_V_12_cast_fu_1293_p1, "OP1_V_12_cast_fu_1293_p1");
    sc_trace(mVcdFile, p_Val2_1_12_fu_1315_p2, "p_Val2_1_12_fu_1315_p2");
    sc_trace(mVcdFile, p_shl2_fu_1341_p3, "p_shl2_fu_1341_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_1349_p1, "p_shl2_cast_fu_1349_p1");
    sc_trace(mVcdFile, p_Val2_1_17_fu_1353_p2, "p_Val2_1_17_fu_1353_p2");
    sc_trace(mVcdFile, p_shl_fu_1389_p3, "p_shl_fu_1389_p3");
    sc_trace(mVcdFile, p_shl1_fu_1401_p3, "p_shl1_fu_1401_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_1397_p1, "p_shl_cast_fu_1397_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_1409_p1, "p_shl1_cast_fu_1409_p1");
    sc_trace(mVcdFile, p_Val2_1_26_fu_1413_p2, "p_Val2_1_26_fu_1413_p2");
    sc_trace(mVcdFile, tmp_35_fu_1474_p1, "tmp_35_fu_1474_p1");
    sc_trace(mVcdFile, tmp_43_fu_1484_p1, "tmp_43_fu_1484_p1");
    sc_trace(mVcdFile, tmp_183_fu_1497_p1, "tmp_183_fu_1497_p1");
    sc_trace(mVcdFile, tmp_183_fu_1497_p4, "tmp_183_fu_1497_p4");
    sc_trace(mVcdFile, tmp_52_fu_1511_p1, "tmp_52_fu_1511_p1");
    sc_trace(mVcdFile, tmp_6_fu_1444_p1, "tmp_6_fu_1444_p1");
    sc_trace(mVcdFile, tmp_9_fu_1447_p1, "tmp_9_fu_1447_p1");
    sc_trace(mVcdFile, tmp_12_fu_1451_p1, "tmp_12_fu_1451_p1");
    sc_trace(mVcdFile, tmp19_fu_1527_p2, "tmp19_fu_1527_p2");
    sc_trace(mVcdFile, tmp18_fu_1521_p2, "tmp18_fu_1521_p2");
    sc_trace(mVcdFile, tmp_15_fu_1454_p1, "tmp_15_fu_1454_p1");
    sc_trace(mVcdFile, tmp_18_fu_1457_p1, "tmp_18_fu_1457_p1");
    sc_trace(mVcdFile, tmp_21_fu_1461_p1, "tmp_21_fu_1461_p1");
    sc_trace(mVcdFile, tmp22_fu_1544_p2, "tmp22_fu_1544_p2");
    sc_trace(mVcdFile, tmp21_fu_1538_p2, "tmp21_fu_1538_p2");
    sc_trace(mVcdFile, tmp20_fu_1550_p2, "tmp20_fu_1550_p2");
    sc_trace(mVcdFile, tmp17_fu_1532_p2, "tmp17_fu_1532_p2");
    sc_trace(mVcdFile, tmp_24_fu_1464_p1, "tmp_24_fu_1464_p1");
    sc_trace(mVcdFile, tmp_27_fu_1467_p1, "tmp_27_fu_1467_p1");
    sc_trace(mVcdFile, tmp_30_fu_1471_p1, "tmp_30_fu_1471_p1");
    sc_trace(mVcdFile, tmp_47_cast_fu_1494_p1, "tmp_47_cast_fu_1494_p1");
    sc_trace(mVcdFile, tmp_50_cast_fu_1507_p1, "tmp_50_cast_fu_1507_p1");
    sc_trace(mVcdFile, tmp_63_fu_1596_p1, "tmp_63_fu_1596_p1");
    sc_trace(mVcdFile, tmp_184_fu_1606_p1, "tmp_184_fu_1606_p1");
    sc_trace(mVcdFile, tmp_184_fu_1606_p4, "tmp_184_fu_1606_p4");
    sc_trace(mVcdFile, tmp_33_fu_1580_p1, "tmp_33_fu_1580_p1");
    sc_trace(mVcdFile, tmp_36_fu_1583_p1, "tmp_36_fu_1583_p1");
    sc_trace(mVcdFile, tmp_39_fu_1586_p1, "tmp_39_fu_1586_p1");
    sc_trace(mVcdFile, tmp29_fu_1630_p2, "tmp29_fu_1630_p2");
    sc_trace(mVcdFile, tmp28_fu_1624_p2, "tmp28_fu_1624_p2");
    sc_trace(mVcdFile, tmp27_fu_1636_p2, "tmp27_fu_1636_p2");
    sc_trace(mVcdFile, tmp24_fu_1620_p2, "tmp24_fu_1620_p2");
    sc_trace(mVcdFile, tmp_44_fu_1593_p1, "tmp_44_fu_1593_p1");
    sc_trace(mVcdFile, tmp34_cast_fu_1654_p1, "tmp34_cast_fu_1654_p1");
    sc_trace(mVcdFile, tmp33_fu_1648_p2, "tmp33_fu_1648_p2");
    sc_trace(mVcdFile, tmp_10_15_cast_fu_1590_p1, "tmp_10_15_cast_fu_1590_p1");
    sc_trace(mVcdFile, tmp45_fu_1663_p2, "tmp45_fu_1663_p2");
    sc_trace(mVcdFile, tmp_72_cast_fu_1616_p1, "tmp_72_cast_fu_1616_p1");
    sc_trace(mVcdFile, tmp_53_fu_1675_p1, "tmp_53_fu_1675_p1");
    sc_trace(mVcdFile, tmp_56_fu_1678_p1, "tmp_56_fu_1678_p1");
    sc_trace(mVcdFile, tmp37_fu_1706_p2, "tmp37_fu_1706_p2");
    sc_trace(mVcdFile, tmp36_fu_1700_p2, "tmp36_fu_1700_p2");
    sc_trace(mVcdFile, tmp_58_fu_1682_p1, "tmp_58_fu_1682_p1");
    sc_trace(mVcdFile, tmp_60_fu_1686_p1, "tmp_60_fu_1686_p1");
    sc_trace(mVcdFile, tmp_62_fu_1690_p1, "tmp_62_fu_1690_p1");
    sc_trace(mVcdFile, tmp41_fu_1723_p2, "tmp41_fu_1723_p2");
    sc_trace(mVcdFile, tmp40_fu_1717_p2, "tmp40_fu_1717_p2");
    sc_trace(mVcdFile, tmp_64_fu_1693_p1, "tmp_64_fu_1693_p1");
    sc_trace(mVcdFile, tmp_66_fu_1696_p1, "tmp_66_fu_1696_p1");
    sc_trace(mVcdFile, tmp44_cast_fu_1741_p1, "tmp44_cast_fu_1741_p1");
    sc_trace(mVcdFile, tmp43_fu_1735_p2, "tmp43_fu_1735_p2");
    sc_trace(mVcdFile, tmp42_fu_1744_p2, "tmp42_fu_1744_p2");
    sc_trace(mVcdFile, tmp39_fu_1729_p2, "tmp39_fu_1729_p2");
    sc_trace(mVcdFile, tmp31_fu_1760_p2, "tmp31_fu_1760_p2");
    sc_trace(mVcdFile, tmp30_fu_1764_p2, "tmp30_fu_1764_p2");
    sc_trace(mVcdFile, tmp15_fu_1756_p2, "tmp15_fu_1756_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_pipeline_idle_pp0, "ap_pipeline_idle_pp0");
    sc_trace(mVcdFile, ap_pipeline_start_pp0, "ap_pipeline_start_pp0");
#endif

    }
}

compute_layer_0_0::~compute_layer_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_mul_18sjbC_x_U86;
    delete myproject_mul_18sjbC_x_U87;
    delete myproject_mul_18sjbC_x_U88;
    delete myproject_mul_18sfYi_x_U89;
    delete myproject_mul_18seOg_x_U90;
    delete myproject_mul_18seOg_x_U91;
    delete myproject_mul_18sg8j_x_U92;
    delete myproject_mul_18seOg_x_U93;
}

void compute_layer_0_0::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void compute_layer_0_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_preg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_enable_reg_pp0_iter0_preg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
             !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_port_reg_data_0_V_read = data_0_V_read.read();
        ap_port_reg_data_11_V_read = data_11_V_read.read();
        ap_port_reg_data_13_V_read = data_13_V_read.read();
        ap_port_reg_data_14_V_read = data_14_V_read.read();
        ap_port_reg_data_15_V_read = data_15_V_read.read();
        ap_port_reg_data_16_V_read = data_16_V_read.read();
        ap_port_reg_data_17_V_read = data_17_V_read.read();
        ap_port_reg_data_18_V_read = data_18_V_read.read();
        ap_port_reg_data_19_V_read = data_19_V_read.read();
        ap_port_reg_data_20_V_read = data_20_V_read.read();
        ap_port_reg_data_21_V_read = data_21_V_read.read();
        ap_port_reg_data_22_V_read = data_22_V_read.read();
        ap_port_reg_data_23_V_read = data_23_V_read.read();
        ap_port_reg_data_24_V_read = data_24_V_read.read();
        ap_port_reg_data_25_V_read = data_25_V_read.read();
        ap_port_reg_data_26_V_read = data_26_V_read.read();
        ap_port_reg_data_27_V_read = data_27_V_read.read();
        ap_port_reg_data_28_V_read = data_28_V_read.read();
        ap_port_reg_data_29_V_read = data_29_V_read.read();
        ap_port_reg_data_2_V_read = data_2_V_read.read();
        ap_port_reg_data_30_V_read = data_30_V_read.read();
        ap_port_reg_data_31_V_read = data_31_V_read.read();
        ap_port_reg_data_4_V_read = data_4_V_read.read();
        ap_port_reg_data_6_V_read = data_6_V_read.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        reg_973 = grp_fu_409_p2.read().range(26, 10);
        reg_977 = grp_fu_408_p2.read().range(26, 10);
        reg_985 = grp_fu_404_p2.read().range(27, 10);
        reg_993 = grp_fu_403_p2.read().range(27, 10);
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) || (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        reg_981 = grp_fu_402_p2.read().range(27, 10);
        reg_989 = grp_fu_405_p2.read().range(26, 10);
    }
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        reg_997 = grp_fu_963_p1.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        tmp16_reg_1965 = tmp16_fu_1556_p2.read();
        tmp25_reg_1970 = tmp25_fu_1562_p2.read();
        tmp26_reg_1975 = tmp26_fu_1568_p2.read();
        tmp34_reg_1980 = tmp34_fu_1574_p2.read();
        tmp_35_reg_1945 = tmp_35_fu_1474_p1.read().range(26, 10);
        tmp_43_reg_1950 = tmp_43_fu_1484_p1.read().range(23, 10);
        tmp_52_reg_1955 = tmp_52_fu_1511_p1.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read()))) {
        tmp23_reg_1990 = tmp23_fu_1642_p2.read();
        tmp32_reg_1995 = tmp32_fu_1657_p2.read();
        tmp44_reg_2000 = tmp44_fu_1669_p2.read();
        tmp_63_reg_1985 = tmp_63_fu_1596_p1.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read()))) {
        tmp35_reg_2005 = tmp35_fu_1711_p2.read();
        tmp38_reg_2010 = tmp38_fu_1750_p2.read();
        tmp_10_2_reg_1860 = p_Val2_1_2_fu_1145_p2.read().range(27, 10);
        tmp_11_reg_1865 = grp_fu_406_p2.read().range(26, 10);
        tmp_14_reg_1870 = p_Val2_1_4_fu_1195_p2.read().range(24, 10);
        tmp_182_reg_1900 = p_Val2_1_17_fu_1353_p2.read().range(21, 10);
        tmp_20_reg_1875 = p_Val2_1_6_fu_1235_p2.read().range(25, 10);
        tmp_23_reg_1880 = grp_fu_407_p2.read().range(26, 10);
        tmp_29_reg_1885 = p_Val2_1_10_fu_1277_p2.read().range(24, 10);
        tmp_32_reg_1890 = p_Val2_1_12_fu_1315_p2.read().range(20, 10);
        tmp_41_reg_1895 = ap_port_reg_data_16_V_read.read().range(17, 3);
        tmp_5_reg_1855 = p_Val2_1_fu_1105_p2.read().range(24, 10);
        tmp_61_reg_1925 = p_Val2_1_26_fu_1413_p2.read().range(25, 10);
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        tmp_10_3_reg_1960 = grp_fu_403_p2.read().range(27, 10);
    }
}

void compute_layer_0_0::thread_OP1_V_10_cast_fu_1261_p1() {
    OP1_V_10_cast_fu_1261_p1 = esl_sext<25,18>(ap_port_reg_data_11_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_11_cast_fu_1036_p1() {
    OP1_V_11_cast_fu_1036_p1 = esl_sext<28,18>(data_12_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_12_cast_fu_1293_p1() {
    OP1_V_12_cast_fu_1293_p1 = esl_sext<21,18>(ap_port_reg_data_13_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_13_cast_fu_1041_p1() {
    OP1_V_13_cast_fu_1041_p1 = esl_sext<27,18>(ap_port_reg_data_14_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_14_cast_fu_1046_p1() {
    OP1_V_14_cast_fu_1046_p1 = esl_sext<26,18>(ap_port_reg_data_15_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_16_cast_fu_1051_p1() {
    OP1_V_16_cast_fu_1051_p1 = esl_sext<24,18>(ap_port_reg_data_17_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_17_cast_fu_1056_p1() {
    OP1_V_17_cast_fu_1056_p1 = esl_sext<28,18>(ap_port_reg_data_18_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_19_cast_fu_1061_p1() {
    OP1_V_19_cast_fu_1061_p1 = esl_sext<25,18>(ap_port_reg_data_20_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_1_cast_fu_1001_p1() {
    OP1_V_1_cast_fu_1001_p1 = esl_sext<27,18>(data_1_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_20_cast_fu_1066_p1() {
    OP1_V_20_cast_fu_1066_p1 = esl_sext<26,18>(ap_port_reg_data_21_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_21_cast_fu_1071_p1() {
    OP1_V_21_cast_fu_1071_p1 = esl_sext<27,18>(ap_port_reg_data_22_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_22_cast_fu_1076_p1() {
    OP1_V_22_cast_fu_1076_p1 = esl_sext<28,18>(ap_port_reg_data_23_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_23_cast_fu_1369_p1() {
    OP1_V_23_cast_fu_1369_p1 = esl_sext<28,18>(ap_port_reg_data_24_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_24_cast_fu_1374_p1() {
    OP1_V_24_cast_fu_1374_p1 = esl_sext<28,18>(ap_port_reg_data_25_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_25_cast_fu_1379_p1() {
    OP1_V_25_cast_fu_1379_p1 = esl_sext<26,18>(ap_port_reg_data_26_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_26_cast_fu_1384_p1() {
    OP1_V_26_cast_fu_1384_p1 = esl_sext<27,18>(ap_port_reg_data_27_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_28_cast_fu_1429_p1() {
    OP1_V_28_cast_fu_1429_p1 = esl_sext<26,18>(ap_port_reg_data_29_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_29_cast_fu_1434_p1() {
    OP1_V_29_cast_fu_1434_p1 = esl_sext<27,18>(ap_port_reg_data_30_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_30_cast_fu_1439_p1() {
    OP1_V_30_cast_fu_1439_p1 = esl_sext<24,18>(ap_port_reg_data_31_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_3_cast_fu_1006_p1() {
    OP1_V_3_cast_fu_1006_p1 = esl_sext<27,18>(data_3_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_5_cast_fu_1011_p1() {
    OP1_V_5_cast_fu_1011_p1 = esl_sext<27,18>(data_5_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_7_cast_fu_1016_p1() {
    OP1_V_7_cast_fu_1016_p1 = esl_sext<28,18>(data_7_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_8_cast_fu_1021_p1() {
    OP1_V_8_cast_fu_1021_p1 = esl_sext<27,18>(data_8_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_9_cast_fu_1026_p1() {
    OP1_V_9_cast_fu_1026_p1 = esl_sext<28,18>(data_9_V_read.read());
}

void compute_layer_0_0::thread_OP1_V_cast_fu_1031_p1() {
    OP1_V_cast_fu_1031_p1 = esl_sext<27,18>(data_10_V_read.read());
}

void compute_layer_0_0::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(0, 0);
}

void compute_layer_0_0::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read().range(1, 1);
}

void compute_layer_0_0::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read().range(2, 2);
}

void compute_layer_0_0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void compute_layer_0_0::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_preg.read();
    }
}

void compute_layer_0_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void compute_layer_0_0::thread_ap_pipeline_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_pipeline_idle_pp0 = ap_const_logic_1;
    } else {
        ap_pipeline_idle_pp0 = ap_const_logic_0;
    }
}

void compute_layer_0_0::thread_ap_pipeline_start_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()))) {
        ap_pipeline_start_pp0 = ap_const_logic_1;
    } else {
        ap_pipeline_start_pp0 = ap_const_logic_0;
    }
}

void compute_layer_0_0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void compute_layer_0_0::thread_ap_return() {
    ap_return = (!tmp30_fu_1764_p2.read().is_01() || !tmp15_fu_1756_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp30_fu_1764_p2.read()) + sc_biguint<18>(tmp15_fu_1756_p2.read()));
}

void compute_layer_0_0::thread_grp_fu_402_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_402_p0 =  (sc_lv<18>) (OP1_V_28_cast_fu_1429_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_402_p0 =  (sc_lv<18>) (OP1_V_17_cast_fu_1056_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_402_p0 =  (sc_lv<18>) (OP1_V_7_cast_fu_1016_p1.read());
        } else {
            grp_fu_402_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_402_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_402_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_402_p1 =  (sc_lv<10>) (ap_const_lv26_3FFFF97);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_402_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE4A);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_402_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE92);
        } else {
            grp_fu_402_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_402_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_403_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_403_p0 =  (sc_lv<18>) (OP1_V_23_cast_fu_1369_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_403_p0 =  (sc_lv<18>) (OP1_V_22_cast_fu_1076_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_403_p0 =  (sc_lv<18>) (OP1_V_11_cast_fu_1036_p1.read());
        } else {
            grp_fu_403_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_403_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_403_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_403_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFEB6);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_403_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFED4);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_403_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE73);
        } else {
            grp_fu_403_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_403_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_404_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_404_p0 =  (sc_lv<18>) (OP1_V_24_cast_fu_1374_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_404_p0 =  (sc_lv<18>) (OP1_V_13_cast_fu_1041_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_404_p0 =  (sc_lv<18>) (OP1_V_9_cast_fu_1026_p1.read());
        } else {
            grp_fu_404_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_404_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_404_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_404_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFE87);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_404_p1 =  (sc_lv<10>) (ap_const_lv27_7FFFF5C);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_404_p1 =  (sc_lv<10>) (ap_const_lv28_FFFFEB3);
        } else {
            grp_fu_404_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_404_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_405_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_405_p0 =  (sc_lv<18>) (OP1_V_21_cast_fu_1071_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_405_p0 =  (sc_lv<18>) (OP1_V_cast_fu_1031_p1.read());
        } else {
            grp_fu_405_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_405_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_405_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_405_p1 =  (sc_lv<10>) (ap_const_lv27_7FFFF0B);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_405_p1 =  (sc_lv<10>) (ap_const_lv27_F2);
        } else {
            grp_fu_405_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        grp_fu_405_p1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_406_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_406_p0 =  (sc_lv<18>) (OP1_V_25_cast_fu_1379_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_406_p0 =  (sc_lv<18>) (OP1_V_14_cast_fu_1046_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_406_p0 =  (sc_lv<18>) (OP1_V_3_cast_fu_1006_p1.read());
        } else {
            grp_fu_406_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_406_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_406_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_406_p1 =  (sc_lv<9>) (ap_const_lv26_4A);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_406_p1 =  (sc_lv<9>) (ap_const_lv26_5C);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_406_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF4B);
        } else {
            grp_fu_406_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_406_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_407_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_407_p0 =  (sc_lv<18>) (OP1_V_30_cast_fu_1439_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_407_p0 =  (sc_lv<18>) (OP1_V_19_cast_fu_1061_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_407_p0 =  (sc_lv<18>) (OP1_V_8_cast_fu_1021_p1.read());
        } else {
            grp_fu_407_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_407_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_407_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_407_p1 =  (sc_lv<9>) (ap_const_lv24_1D);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_407_p1 =  (sc_lv<9>) (ap_const_lv25_32);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_407_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF52);
        } else {
            grp_fu_407_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_407_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_408_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_408_p0 =  (sc_lv<18>) (OP1_V_26_cast_fu_1384_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_408_p0 =  (sc_lv<18>) (OP1_V_16_cast_fu_1051_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_408_p0 =  (sc_lv<18>) (OP1_V_5_cast_fu_1011_p1.read());
        } else {
            grp_fu_408_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_408_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_408_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_408_p1 =  (sc_lv<9>) (ap_const_lv27_9F);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_408_p1 =  (sc_lv<9>) (ap_const_lv24_19);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_408_p1 =  (sc_lv<9>) (ap_const_lv27_BF);
        } else {
            grp_fu_408_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_408_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_409_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_409_p0 =  (sc_lv<18>) (OP1_V_29_cast_fu_1434_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_409_p0 =  (sc_lv<18>) (OP1_V_20_cast_fu_1066_p1.read());
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_409_p0 =  (sc_lv<18>) (OP1_V_1_cast_fu_1001_p1.read());
        } else {
            grp_fu_409_p0 = "XXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_409_p0 = "XXXXXXXXXXXXXXXXXX";
    }
}

void compute_layer_0_0::thread_grp_fu_409_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage2.read())) {
            grp_fu_409_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF46);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage1.read())) {
            grp_fu_409_p1 =  (sc_lv<9>) (ap_const_lv26_3FFFF9F);
        } else if (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1)) {
            grp_fu_409_p1 =  (sc_lv<9>) (ap_const_lv27_7FFFF71);
        } else {
            grp_fu_409_p1 =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        grp_fu_409_p1 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void compute_layer_0_0::thread_grp_fu_963_p1() {
    grp_fu_963_p1 =  (sc_lv<26>) (grp_fu_406_p2.read());
}

void compute_layer_0_0::thread_p_Val2_1_10_fu_1277_p2() {
    p_Val2_1_10_fu_1277_p2 = (!p_shl4_cast_fu_1273_p1.read().is_01() || !OP1_V_10_cast_fu_1261_p1.read().is_01())? sc_lv<25>(): (sc_bigint<25>(p_shl4_cast_fu_1273_p1.read()) + sc_bigint<25>(OP1_V_10_cast_fu_1261_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_12_fu_1315_p2() {
    p_Val2_1_12_fu_1315_p2 = (!p_neg_fu_1309_p2.read().is_01() || !OP1_V_12_cast_fu_1293_p1.read().is_01())? sc_lv<21>(): (sc_biguint<21>(p_neg_fu_1309_p2.read()) - sc_bigint<21>(OP1_V_12_cast_fu_1293_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_17_fu_1353_p2() {
    p_Val2_1_17_fu_1353_p2 = (!ap_const_lv22_0.is_01() || !p_shl2_cast_fu_1349_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(ap_const_lv22_0) - sc_bigint<22>(p_shl2_cast_fu_1349_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_26_fu_1413_p2() {
    p_Val2_1_26_fu_1413_p2 = (!p_shl_cast_fu_1397_p1.read().is_01() || !p_shl1_cast_fu_1409_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(p_shl_cast_fu_1397_p1.read()) - sc_bigint<26>(p_shl1_cast_fu_1409_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_2_fu_1145_p2() {
    p_Val2_1_2_fu_1145_p2 = (!p_shl11_cast_fu_1141_p1.read().is_01() || !p_shl9_cast_fu_1129_p1.read().is_01())? sc_lv<28>(): (sc_bigint<28>(p_shl11_cast_fu_1141_p1.read()) - sc_bigint<28>(p_shl9_cast_fu_1129_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_4_fu_1195_p2() {
    p_Val2_1_4_fu_1195_p2 = (!p_shl7_cast_fu_1179_p1.read().is_01() || !p_shl8_cast_fu_1191_p1.read().is_01())? sc_lv<25>(): (sc_bigint<25>(p_shl7_cast_fu_1179_p1.read()) + sc_bigint<25>(p_shl8_cast_fu_1191_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_6_fu_1235_p2() {
    p_Val2_1_6_fu_1235_p2 = (!p_shl5_cast_fu_1219_p1.read().is_01() || !p_shl6_cast_fu_1231_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(p_shl5_cast_fu_1219_p1.read()) + sc_bigint<26>(p_shl6_cast_fu_1231_p1.read()));
}

void compute_layer_0_0::thread_p_Val2_1_fu_1105_p2() {
    p_Val2_1_fu_1105_p2 = (!p_shl14_cast_fu_1101_p1.read().is_01() || !p_shl12_cast_fu_1089_p1.read().is_01())? sc_lv<25>(): (sc_bigint<25>(p_shl14_cast_fu_1101_p1.read()) - sc_bigint<25>(p_shl12_cast_fu_1089_p1.read()));
}

void compute_layer_0_0::thread_p_neg_fu_1309_p2() {
    p_neg_fu_1309_p2 = (!ap_const_lv21_0.is_01() || !p_shl3_cast_fu_1305_p1.read().is_01())? sc_lv<21>(): (sc_biguint<21>(ap_const_lv21_0) - sc_bigint<21>(p_shl3_cast_fu_1305_p1.read()));
}

void compute_layer_0_0::thread_p_shl10_fu_1081_p3() {
    p_shl10_fu_1081_p3 = esl_concat<18,6>(ap_port_reg_data_0_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0::thread_p_shl11_cast_fu_1141_p1() {
    p_shl11_cast_fu_1141_p1 = esl_sext<28,24>(p_shl11_fu_1133_p3.read());
}

void compute_layer_0_0::thread_p_shl11_fu_1133_p3() {
    p_shl11_fu_1133_p3 = esl_concat<18,6>(ap_port_reg_data_2_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0::thread_p_shl12_cast_fu_1089_p1() {
    p_shl12_cast_fu_1089_p1 = esl_sext<25,24>(p_shl10_fu_1081_p3.read());
}

void compute_layer_0_0::thread_p_shl12_fu_1093_p3() {
    p_shl12_fu_1093_p3 = esl_concat<18,2>(ap_port_reg_data_0_V_read.read(), ap_const_lv2_0);
}

void compute_layer_0_0::thread_p_shl14_cast_fu_1101_p1() {
    p_shl14_cast_fu_1101_p1 = esl_sext<25,20>(p_shl12_fu_1093_p3.read());
}

void compute_layer_0_0::thread_p_shl1_cast_fu_1409_p1() {
    p_shl1_cast_fu_1409_p1 = esl_sext<26,21>(p_shl1_fu_1401_p3.read());
}

void compute_layer_0_0::thread_p_shl1_fu_1401_p3() {
    p_shl1_fu_1401_p3 = esl_concat<18,3>(ap_port_reg_data_28_V_read.read(), ap_const_lv3_0);
}

void compute_layer_0_0::thread_p_shl2_cast_fu_1349_p1() {
    p_shl2_cast_fu_1349_p1 = esl_sext<22,21>(p_shl2_fu_1341_p3.read());
}

void compute_layer_0_0::thread_p_shl2_fu_1341_p3() {
    p_shl2_fu_1341_p3 = esl_concat<18,3>(ap_port_reg_data_19_V_read.read(), ap_const_lv3_0);
}

void compute_layer_0_0::thread_p_shl3_cast_fu_1305_p1() {
    p_shl3_cast_fu_1305_p1 = esl_sext<21,20>(p_shl3_fu_1297_p3.read());
}

void compute_layer_0_0::thread_p_shl3_fu_1297_p3() {
    p_shl3_fu_1297_p3 = esl_concat<18,2>(ap_port_reg_data_13_V_read.read(), ap_const_lv2_0);
}

void compute_layer_0_0::thread_p_shl4_cast_fu_1273_p1() {
    p_shl4_cast_fu_1273_p1 = esl_sext<25,24>(p_shl4_fu_1265_p3.read());
}

void compute_layer_0_0::thread_p_shl4_fu_1265_p3() {
    p_shl4_fu_1265_p3 = esl_concat<18,6>(ap_port_reg_data_11_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0::thread_p_shl5_cast_fu_1219_p1() {
    p_shl5_cast_fu_1219_p1 = esl_sext<26,25>(p_shl5_fu_1211_p3.read());
}

void compute_layer_0_0::thread_p_shl5_fu_1211_p3() {
    p_shl5_fu_1211_p3 = esl_concat<18,7>(ap_port_reg_data_6_V_read.read(), ap_const_lv7_0);
}

void compute_layer_0_0::thread_p_shl6_cast_fu_1231_p1() {
    p_shl6_cast_fu_1231_p1 = esl_sext<26,23>(p_shl6_fu_1223_p3.read());
}

void compute_layer_0_0::thread_p_shl6_fu_1223_p3() {
    p_shl6_fu_1223_p3 = esl_concat<18,5>(ap_port_reg_data_6_V_read.read(), ap_const_lv5_0);
}

void compute_layer_0_0::thread_p_shl7_cast_fu_1179_p1() {
    p_shl7_cast_fu_1179_p1 = esl_sext<25,24>(p_shl7_fu_1171_p3.read());
}

void compute_layer_0_0::thread_p_shl7_fu_1171_p3() {
    p_shl7_fu_1171_p3 = esl_concat<18,6>(ap_port_reg_data_4_V_read.read(), ap_const_lv6_0);
}

void compute_layer_0_0::thread_p_shl8_cast_fu_1191_p1() {
    p_shl8_cast_fu_1191_p1 = esl_sext<25,19>(p_shl8_fu_1183_p3.read());
}

void compute_layer_0_0::thread_p_shl8_fu_1183_p3() {
    p_shl8_fu_1183_p3 = esl_concat<18,1>(ap_port_reg_data_4_V_read.read(), ap_const_lv1_0);
}

void compute_layer_0_0::thread_p_shl9_cast_fu_1129_p1() {
    p_shl9_cast_fu_1129_p1 = esl_sext<28,27>(p_shl9_fu_1121_p3.read());
}

void compute_layer_0_0::thread_p_shl9_fu_1121_p3() {
    p_shl9_fu_1121_p3 = esl_concat<18,9>(ap_port_reg_data_2_V_read.read(), ap_const_lv9_0);
}

void compute_layer_0_0::thread_p_shl_cast_fu_1397_p1() {
    p_shl_cast_fu_1397_p1 = esl_sext<26,25>(p_shl_fu_1389_p3.read());
}

void compute_layer_0_0::thread_p_shl_fu_1389_p3() {
    p_shl_fu_1389_p3 = esl_concat<18,7>(ap_port_reg_data_28_V_read.read(), ap_const_lv7_0);
}

void compute_layer_0_0::thread_tmp15_fu_1756_p2() {
    tmp15_fu_1756_p2 = (!tmp23_reg_1990.read().is_01() || !tmp16_reg_1965.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp23_reg_1990.read()) + sc_biguint<18>(tmp16_reg_1965.read()));
}

void compute_layer_0_0::thread_tmp16_fu_1556_p2() {
    tmp16_fu_1556_p2 = (!tmp20_fu_1550_p2.read().is_01() || !tmp17_fu_1532_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp20_fu_1550_p2.read()) + sc_biguint<18>(tmp17_fu_1532_p2.read()));
}

void compute_layer_0_0::thread_tmp17_fu_1532_p2() {
    tmp17_fu_1532_p2 = (!tmp19_fu_1527_p2.read().is_01() || !tmp18_fu_1521_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp19_fu_1527_p2.read()) + sc_biguint<18>(tmp18_fu_1521_p2.read()));
}

void compute_layer_0_0::thread_tmp18_fu_1521_p2() {
    tmp18_fu_1521_p2 = (!tmp_6_fu_1444_p1.read().is_01() || !tmp_9_fu_1447_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_6_fu_1444_p1.read()) + sc_bigint<18>(tmp_9_fu_1447_p1.read()));
}

void compute_layer_0_0::thread_tmp19_fu_1527_p2() {
    tmp19_fu_1527_p2 = (!tmp_10_2_reg_1860.read().is_01() || !tmp_12_fu_1451_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_10_2_reg_1860.read()) + sc_bigint<18>(tmp_12_fu_1451_p1.read()));
}

void compute_layer_0_0::thread_tmp20_fu_1550_p2() {
    tmp20_fu_1550_p2 = (!tmp22_fu_1544_p2.read().is_01() || !tmp21_fu_1538_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp22_fu_1544_p2.read()) + sc_biguint<18>(tmp21_fu_1538_p2.read()));
}

void compute_layer_0_0::thread_tmp21_fu_1538_p2() {
    tmp21_fu_1538_p2 = (!tmp_15_fu_1454_p1.read().is_01() || !tmp_18_fu_1457_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_15_fu_1454_p1.read()) + sc_bigint<18>(tmp_18_fu_1457_p1.read()));
}

void compute_layer_0_0::thread_tmp22_fu_1544_p2() {
    tmp22_fu_1544_p2 = (!tmp_21_fu_1461_p1.read().is_01() || !reg_981.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_21_fu_1461_p1.read()) + sc_biguint<18>(reg_981.read()));
}

void compute_layer_0_0::thread_tmp23_fu_1642_p2() {
    tmp23_fu_1642_p2 = (!tmp27_fu_1636_p2.read().is_01() || !tmp24_fu_1620_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp27_fu_1636_p2.read()) + sc_biguint<18>(tmp24_fu_1620_p2.read()));
}

void compute_layer_0_0::thread_tmp24_fu_1620_p2() {
    tmp24_fu_1620_p2 = (!tmp26_reg_1975.read().is_01() || !tmp25_reg_1970.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp26_reg_1975.read()) + sc_biguint<18>(tmp25_reg_1970.read()));
}

void compute_layer_0_0::thread_tmp25_fu_1562_p2() {
    tmp25_fu_1562_p2 = (!tmp_24_fu_1464_p1.read().is_01() || !reg_985.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_24_fu_1464_p1.read()) + sc_biguint<18>(reg_985.read()));
}

void compute_layer_0_0::thread_tmp26_fu_1568_p2() {
    tmp26_fu_1568_p2 = (!tmp_27_fu_1467_p1.read().is_01() || !tmp_30_fu_1471_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_27_fu_1467_p1.read()) + sc_bigint<18>(tmp_30_fu_1471_p1.read()));
}

void compute_layer_0_0::thread_tmp27_fu_1636_p2() {
    tmp27_fu_1636_p2 = (!tmp29_fu_1630_p2.read().is_01() || !tmp28_fu_1624_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp29_fu_1630_p2.read()) + sc_biguint<18>(tmp28_fu_1624_p2.read()));
}

void compute_layer_0_0::thread_tmp28_fu_1624_p2() {
    tmp28_fu_1624_p2 = (!reg_993.read().is_01() || !tmp_33_fu_1580_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(reg_993.read()) + sc_bigint<18>(tmp_33_fu_1580_p1.read()));
}

void compute_layer_0_0::thread_tmp29_fu_1630_p2() {
    tmp29_fu_1630_p2 = (!tmp_36_fu_1583_p1.read().is_01() || !tmp_39_fu_1586_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_36_fu_1583_p1.read()) + sc_bigint<18>(tmp_39_fu_1586_p1.read()));
}

void compute_layer_0_0::thread_tmp30_fu_1764_p2() {
    tmp30_fu_1764_p2 = (!tmp38_reg_2010.read().is_01() || !tmp31_fu_1760_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp38_reg_2010.read()) + sc_biguint<18>(tmp31_fu_1760_p2.read()));
}

void compute_layer_0_0::thread_tmp31_fu_1760_p2() {
    tmp31_fu_1760_p2 = (!tmp35_reg_2005.read().is_01() || !tmp32_reg_1995.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp35_reg_2005.read()) + sc_biguint<18>(tmp32_reg_1995.read()));
}

void compute_layer_0_0::thread_tmp32_fu_1657_p2() {
    tmp32_fu_1657_p2 = (!tmp34_cast_fu_1654_p1.read().is_01() || !tmp33_fu_1648_p2.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp34_cast_fu_1654_p1.read()) + sc_biguint<18>(tmp33_fu_1648_p2.read()));
}

void compute_layer_0_0::thread_tmp33_fu_1648_p2() {
    tmp33_fu_1648_p2 = (!tmp_44_fu_1593_p1.read().is_01() || !reg_981.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_44_fu_1593_p1.read()) + sc_biguint<18>(reg_981.read()));
}

void compute_layer_0_0::thread_tmp34_cast_fu_1654_p1() {
    tmp34_cast_fu_1654_p1 = esl_sext<18,16>(tmp34_reg_1980.read());
}

void compute_layer_0_0::thread_tmp34_fu_1574_p2() {
    tmp34_fu_1574_p2 = (!tmp_47_cast_fu_1494_p1.read().is_01() || !tmp_50_cast_fu_1507_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_47_cast_fu_1494_p1.read()) + sc_bigint<16>(tmp_50_cast_fu_1507_p1.read()));
}

void compute_layer_0_0::thread_tmp35_fu_1711_p2() {
    tmp35_fu_1711_p2 = (!tmp37_fu_1706_p2.read().is_01() || !tmp36_fu_1700_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp37_fu_1706_p2.read()) + sc_biguint<18>(tmp36_fu_1700_p2.read()));
}

void compute_layer_0_0::thread_tmp36_fu_1700_p2() {
    tmp36_fu_1700_p2 = (!tmp_53_fu_1675_p1.read().is_01() || !tmp_56_fu_1678_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_53_fu_1675_p1.read()) + sc_bigint<18>(tmp_56_fu_1678_p1.read()));
}

void compute_layer_0_0::thread_tmp37_fu_1706_p2() {
    tmp37_fu_1706_p2 = (!tmp_10_3_reg_1960.read().is_01() || !reg_993.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_10_3_reg_1960.read()) + sc_biguint<18>(reg_993.read()));
}

void compute_layer_0_0::thread_tmp38_fu_1750_p2() {
    tmp38_fu_1750_p2 = (!tmp42_fu_1744_p2.read().is_01() || !tmp39_fu_1729_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp42_fu_1744_p2.read()) + sc_biguint<18>(tmp39_fu_1729_p2.read()));
}

void compute_layer_0_0::thread_tmp39_fu_1729_p2() {
    tmp39_fu_1729_p2 = (!tmp41_fu_1723_p2.read().is_01() || !tmp40_fu_1717_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp41_fu_1723_p2.read()) + sc_biguint<18>(tmp40_fu_1717_p2.read()));
}

void compute_layer_0_0::thread_tmp40_fu_1717_p2() {
    tmp40_fu_1717_p2 = (!reg_985.read().is_01() || !tmp_58_fu_1682_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(reg_985.read()) + sc_bigint<18>(tmp_58_fu_1682_p1.read()));
}

void compute_layer_0_0::thread_tmp41_fu_1723_p2() {
    tmp41_fu_1723_p2 = (!tmp_60_fu_1686_p1.read().is_01() || !tmp_62_fu_1690_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_60_fu_1686_p1.read()) + sc_bigint<18>(tmp_62_fu_1690_p1.read()));
}

void compute_layer_0_0::thread_tmp42_fu_1744_p2() {
    tmp42_fu_1744_p2 = (!tmp44_cast_fu_1741_p1.read().is_01() || !tmp43_fu_1735_p2.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp44_cast_fu_1741_p1.read()) + sc_biguint<18>(tmp43_fu_1735_p2.read()));
}

void compute_layer_0_0::thread_tmp43_fu_1735_p2() {
    tmp43_fu_1735_p2 = (!tmp_64_fu_1693_p1.read().is_01() || !tmp_66_fu_1696_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(tmp_64_fu_1693_p1.read()) + sc_bigint<18>(tmp_66_fu_1696_p1.read()));
}

void compute_layer_0_0::thread_tmp44_cast_fu_1741_p1() {
    tmp44_cast_fu_1741_p1 = esl_sext<18,16>(tmp44_reg_2000.read());
}

void compute_layer_0_0::thread_tmp44_fu_1669_p2() {
    tmp44_fu_1669_p2 = (!tmp45_fu_1663_p2.read().is_01() || !tmp_72_cast_fu_1616_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp45_fu_1663_p2.read()) + sc_bigint<16>(tmp_72_cast_fu_1616_p1.read()));
}

void compute_layer_0_0::thread_tmp45_fu_1663_p2() {
    tmp45_fu_1663_p2 = (!tmp_10_15_cast_fu_1590_p1.read().is_01() || !ap_const_lv16_FF86.is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_10_15_cast_fu_1590_p1.read()) + sc_bigint<16>(ap_const_lv16_FF86));
}

void compute_layer_0_0::thread_tmp_10_15_cast_fu_1590_p1() {
    tmp_10_15_cast_fu_1590_p1 = esl_sext<16,15>(tmp_41_reg_1895.read());
}

void compute_layer_0_0::thread_tmp_12_fu_1451_p1() {
    tmp_12_fu_1451_p1 = esl_sext<18,17>(tmp_11_reg_1865.read());
}

void compute_layer_0_0::thread_tmp_15_fu_1454_p1() {
    tmp_15_fu_1454_p1 = esl_sext<18,15>(tmp_14_reg_1870.read());
}

void compute_layer_0_0::thread_tmp_183_fu_1497_p1() {
    tmp_183_fu_1497_p1 =  (sc_lv<25>) (grp_fu_407_p2.read());
}

void compute_layer_0_0::thread_tmp_183_fu_1497_p4() {
    tmp_183_fu_1497_p4 = tmp_183_fu_1497_p1.read().range(24, 10);
}

void compute_layer_0_0::thread_tmp_184_fu_1606_p1() {
    tmp_184_fu_1606_p1 =  (sc_lv<24>) (grp_fu_407_p2.read());
}

void compute_layer_0_0::thread_tmp_184_fu_1606_p4() {
    tmp_184_fu_1606_p4 = tmp_184_fu_1606_p1.read().range(23, 10);
}

void compute_layer_0_0::thread_tmp_18_fu_1457_p1() {
    tmp_18_fu_1457_p1 = esl_sext<18,17>(reg_977.read());
}

void compute_layer_0_0::thread_tmp_21_fu_1461_p1() {
    tmp_21_fu_1461_p1 = esl_sext<18,16>(tmp_20_reg_1875.read());
}

void compute_layer_0_0::thread_tmp_24_fu_1464_p1() {
    tmp_24_fu_1464_p1 = esl_sext<18,17>(tmp_23_reg_1880.read());
}

void compute_layer_0_0::thread_tmp_27_fu_1467_p1() {
    tmp_27_fu_1467_p1 = esl_sext<18,17>(reg_989.read());
}

void compute_layer_0_0::thread_tmp_30_fu_1471_p1() {
    tmp_30_fu_1471_p1 = esl_sext<18,15>(tmp_29_reg_1885.read());
}

void compute_layer_0_0::thread_tmp_33_fu_1580_p1() {
    tmp_33_fu_1580_p1 = esl_sext<18,11>(tmp_32_reg_1890.read());
}

void compute_layer_0_0::thread_tmp_35_fu_1474_p1() {
    tmp_35_fu_1474_p1 =  (sc_lv<27>) (grp_fu_404_p2.read());
}

void compute_layer_0_0::thread_tmp_36_fu_1583_p1() {
    tmp_36_fu_1583_p1 = esl_sext<18,17>(tmp_35_reg_1945.read());
}

void compute_layer_0_0::thread_tmp_39_fu_1586_p1() {
    tmp_39_fu_1586_p1 = esl_sext<18,16>(reg_997.read());
}

void compute_layer_0_0::thread_tmp_43_fu_1484_p1() {
    tmp_43_fu_1484_p1 =  (sc_lv<24>) (grp_fu_408_p2.read());
}

void compute_layer_0_0::thread_tmp_44_fu_1593_p1() {
    tmp_44_fu_1593_p1 = esl_sext<18,14>(tmp_43_reg_1950.read());
}

void compute_layer_0_0::thread_tmp_47_cast_fu_1494_p1() {
    tmp_47_cast_fu_1494_p1 = esl_sext<16,12>(tmp_182_reg_1900.read());
}

void compute_layer_0_0::thread_tmp_50_cast_fu_1507_p1() {
    tmp_50_cast_fu_1507_p1 = esl_sext<16,15>(tmp_183_fu_1497_p4.read());
}

void compute_layer_0_0::thread_tmp_52_fu_1511_p1() {
    tmp_52_fu_1511_p1 =  (sc_lv<26>) (grp_fu_409_p2.read());
}

void compute_layer_0_0::thread_tmp_53_fu_1675_p1() {
    tmp_53_fu_1675_p1 = esl_sext<18,16>(tmp_52_reg_1955.read());
}

void compute_layer_0_0::thread_tmp_56_fu_1678_p1() {
    tmp_56_fu_1678_p1 = esl_sext<18,17>(reg_989.read());
}

void compute_layer_0_0::thread_tmp_58_fu_1682_p1() {
    tmp_58_fu_1682_p1 = esl_sext<18,16>(reg_997.read());
}

void compute_layer_0_0::thread_tmp_60_fu_1686_p1() {
    tmp_60_fu_1686_p1 = esl_sext<18,17>(reg_977.read());
}

void compute_layer_0_0::thread_tmp_62_fu_1690_p1() {
    tmp_62_fu_1690_p1 = esl_sext<18,16>(tmp_61_reg_1925.read());
}

void compute_layer_0_0::thread_tmp_63_fu_1596_p1() {
    tmp_63_fu_1596_p1 =  (sc_lv<26>) (grp_fu_402_p2.read());
}

void compute_layer_0_0::thread_tmp_64_fu_1693_p1() {
    tmp_64_fu_1693_p1 = esl_sext<18,16>(tmp_63_reg_1985.read());
}

void compute_layer_0_0::thread_tmp_66_fu_1696_p1() {
    tmp_66_fu_1696_p1 = esl_sext<18,17>(reg_973.read());
}

void compute_layer_0_0::thread_tmp_6_fu_1444_p1() {
    tmp_6_fu_1444_p1 = esl_sext<18,15>(tmp_5_reg_1855.read());
}

void compute_layer_0_0::thread_tmp_72_cast_fu_1616_p1() {
    tmp_72_cast_fu_1616_p1 = esl_sext<16,14>(tmp_184_fu_1606_p4.read());
}

void compute_layer_0_0::thread_tmp_9_fu_1447_p1() {
    tmp_9_fu_1447_p1 = esl_sext<18,17>(reg_973.read());
}

void compute_layer_0_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_pipeline_idle_pp0.read()) && !(!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_pipeline_start_pp0.read())) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_pipeline_idle_pp0.read())) || (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_pipeline_start_pp0.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

