// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_myproject (
ap_fixed<18, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> data[10],
ap_fixed<18, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> res[1],
unsigned short& const_size_in,
unsigned short& const_size_out);
