// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module compute_layer_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 3'b1;
parameter    ap_ST_fsm_pp0_stage1 = 3'b10;
parameter    ap_ST_fsm_pp0_stage2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv28_FFFFE92 = 28'b1111111111111111111010010010;
parameter    ap_const_lv28_FFFFE4A = 28'b1111111111111111111001001010;
parameter    ap_const_lv26_3FFFF97 = 26'b11111111111111111110010111;
parameter    ap_const_lv28_FFFFE73 = 28'b1111111111111111111001110011;
parameter    ap_const_lv28_FFFFED4 = 28'b1111111111111111111011010100;
parameter    ap_const_lv28_FFFFEB6 = 28'b1111111111111111111010110110;
parameter    ap_const_lv28_FFFFEB3 = 28'b1111111111111111111010110011;
parameter    ap_const_lv27_7FFFF5C = 27'b111111111111111111101011100;
parameter    ap_const_lv28_FFFFE87 = 28'b1111111111111111111010000111;
parameter    ap_const_lv27_F2 = 27'b11110010;
parameter    ap_const_lv27_7FFFF0B = 27'b111111111111111111100001011;
parameter    ap_const_lv27_7FFFF4B = 27'b111111111111111111101001011;
parameter    ap_const_lv26_5C = 26'b1011100;
parameter    ap_const_lv26_4A = 26'b1001010;
parameter    ap_const_lv27_7FFFF52 = 27'b111111111111111111101010010;
parameter    ap_const_lv25_32 = 25'b110010;
parameter    ap_const_lv24_1D = 24'b11101;
parameter    ap_const_lv27_BF = 27'b10111111;
parameter    ap_const_lv24_19 = 24'b11001;
parameter    ap_const_lv27_9F = 27'b10011111;
parameter    ap_const_lv27_7FFFF71 = 27'b111111111111111111101110001;
parameter    ap_const_lv26_3FFFF9F = 26'b11111111111111111110011111;
parameter    ap_const_lv27_7FFFF46 = 27'b111111111111111111101000110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv21_0 = 21'b000000000000000000000;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv22_0 = 22'b0000000000000000000000;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv16_FF86 = 16'b1111111110000110;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] data_0_V_read;
input  [17:0] data_1_V_read;
input  [17:0] data_2_V_read;
input  [17:0] data_3_V_read;
input  [17:0] data_4_V_read;
input  [17:0] data_5_V_read;
input  [17:0] data_6_V_read;
input  [17:0] data_7_V_read;
input  [17:0] data_8_V_read;
input  [17:0] data_9_V_read;
input  [17:0] data_10_V_read;
input  [17:0] data_11_V_read;
input  [17:0] data_12_V_read;
input  [17:0] data_13_V_read;
input  [17:0] data_14_V_read;
input  [17:0] data_15_V_read;
input  [17:0] data_16_V_read;
input  [17:0] data_17_V_read;
input  [17:0] data_18_V_read;
input  [17:0] data_19_V_read;
input  [17:0] data_20_V_read;
input  [17:0] data_21_V_read;
input  [17:0] data_22_V_read;
input  [17:0] data_23_V_read;
input  [17:0] data_24_V_read;
input  [17:0] data_25_V_read;
input  [17:0] data_26_V_read;
input  [17:0] data_27_V_read;
input  [17:0] data_28_V_read;
input  [17:0] data_29_V_read;
input  [17:0] data_30_V_read;
input  [17:0] data_31_V_read;
output  [17:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
wire   [0:0] ap_CS_fsm_pp0_stage2;
reg   [16:0] reg_973;
wire   [0:0] ap_CS_fsm_pp0_stage1;
reg   [16:0] reg_977;
reg   [17:0] reg_981;
reg   [17:0] reg_985;
reg   [16:0] reg_989;
reg   [17:0] reg_993;
reg   [15:0] reg_997;
wire  signed [26:0] OP1_V_1_cast_fu_1001_p1;
wire  signed [26:0] OP1_V_3_cast_fu_1006_p1;
wire  signed [26:0] OP1_V_5_cast_fu_1011_p1;
wire  signed [27:0] OP1_V_7_cast_fu_1016_p1;
wire  signed [26:0] OP1_V_8_cast_fu_1021_p1;
wire  signed [27:0] OP1_V_9_cast_fu_1026_p1;
wire  signed [26:0] OP1_V_cast_fu_1031_p1;
wire  signed [27:0] OP1_V_11_cast_fu_1036_p1;
wire  signed [26:0] OP1_V_13_cast_fu_1041_p1;
wire  signed [25:0] OP1_V_14_cast_fu_1046_p1;
wire  signed [23:0] OP1_V_16_cast_fu_1051_p1;
wire  signed [27:0] OP1_V_17_cast_fu_1056_p1;
wire  signed [24:0] OP1_V_19_cast_fu_1061_p1;
wire  signed [25:0] OP1_V_20_cast_fu_1066_p1;
wire  signed [26:0] OP1_V_21_cast_fu_1071_p1;
wire  signed [27:0] OP1_V_22_cast_fu_1076_p1;
reg   [14:0] tmp_5_reg_1855;
reg   [17:0] tmp_10_2_reg_1860;
reg   [16:0] tmp_11_reg_1865;
reg   [14:0] tmp_14_reg_1870;
reg   [15:0] tmp_20_reg_1875;
reg   [16:0] tmp_23_reg_1880;
reg   [14:0] tmp_29_reg_1885;
reg   [10:0] tmp_32_reg_1890;
reg   [14:0] tmp_41_reg_1895;
reg   [11:0] tmp_182_reg_1900;
wire  signed [27:0] OP1_V_23_cast_fu_1369_p1;
wire  signed [27:0] OP1_V_24_cast_fu_1374_p1;
wire  signed [25:0] OP1_V_25_cast_fu_1379_p1;
wire  signed [26:0] OP1_V_26_cast_fu_1384_p1;
reg   [15:0] tmp_61_reg_1925;
wire  signed [25:0] OP1_V_28_cast_fu_1429_p1;
wire  signed [26:0] OP1_V_29_cast_fu_1434_p1;
wire  signed [23:0] OP1_V_30_cast_fu_1439_p1;
reg   [16:0] tmp_35_reg_1945;
reg   [13:0] tmp_43_reg_1950;
reg   [15:0] tmp_52_reg_1955;
reg   [17:0] tmp_10_3_reg_1960;
wire   [17:0] tmp16_fu_1556_p2;
reg   [17:0] tmp16_reg_1965;
wire   [17:0] tmp25_fu_1562_p2;
reg   [17:0] tmp25_reg_1970;
wire   [17:0] tmp26_fu_1568_p2;
reg   [17:0] tmp26_reg_1975;
wire   [15:0] tmp34_fu_1574_p2;
reg   [15:0] tmp34_reg_1980;
reg   [15:0] tmp_63_reg_1985;
wire   [17:0] tmp23_fu_1642_p2;
reg   [17:0] tmp23_reg_1990;
wire   [17:0] tmp32_fu_1657_p2;
reg   [17:0] tmp32_reg_1995;
wire   [15:0] tmp44_fu_1669_p2;
reg   [15:0] tmp44_reg_2000;
wire   [17:0] tmp35_fu_1711_p2;
reg   [17:0] tmp35_reg_2005;
wire   [17:0] tmp38_fu_1750_p2;
reg   [17:0] tmp38_reg_2010;
reg    ap_enable_reg_pp0_iter0_preg;
reg   [17:0] ap_port_reg_data_0_V_read;
reg   [17:0] ap_port_reg_data_2_V_read;
reg   [17:0] ap_port_reg_data_4_V_read;
reg   [17:0] ap_port_reg_data_6_V_read;
reg   [17:0] ap_port_reg_data_11_V_read;
reg   [17:0] ap_port_reg_data_13_V_read;
reg   [17:0] ap_port_reg_data_14_V_read;
reg   [17:0] ap_port_reg_data_15_V_read;
reg   [17:0] ap_port_reg_data_16_V_read;
reg   [17:0] ap_port_reg_data_17_V_read;
reg   [17:0] ap_port_reg_data_18_V_read;
reg   [17:0] ap_port_reg_data_19_V_read;
reg   [17:0] ap_port_reg_data_20_V_read;
reg   [17:0] ap_port_reg_data_21_V_read;
reg   [17:0] ap_port_reg_data_22_V_read;
reg   [17:0] ap_port_reg_data_23_V_read;
reg   [17:0] ap_port_reg_data_24_V_read;
reg   [17:0] ap_port_reg_data_25_V_read;
reg   [17:0] ap_port_reg_data_26_V_read;
reg   [17:0] ap_port_reg_data_27_V_read;
reg   [17:0] ap_port_reg_data_28_V_read;
reg   [17:0] ap_port_reg_data_29_V_read;
reg   [17:0] ap_port_reg_data_30_V_read;
reg   [17:0] ap_port_reg_data_31_V_read;
reg  signed [17:0] grp_fu_402_p0;
reg  signed [9:0] grp_fu_402_p1;
reg  signed [17:0] grp_fu_403_p0;
reg  signed [9:0] grp_fu_403_p1;
reg  signed [17:0] grp_fu_404_p0;
reg  signed [9:0] grp_fu_404_p1;
reg  signed [17:0] grp_fu_405_p0;
reg  signed [9:0] grp_fu_405_p1;
reg  signed [17:0] grp_fu_406_p0;
reg  signed [8:0] grp_fu_406_p1;
reg  signed [17:0] grp_fu_407_p0;
reg  signed [8:0] grp_fu_407_p1;
reg  signed [17:0] grp_fu_408_p0;
reg   [8:0] grp_fu_408_p1;
reg  signed [17:0] grp_fu_409_p0;
reg  signed [8:0] grp_fu_409_p1;
wire   [26:0] grp_fu_409_p2;
wire   [26:0] grp_fu_408_p2;
wire   [27:0] grp_fu_402_p2;
wire   [27:0] grp_fu_404_p2;
wire   [26:0] grp_fu_405_p2;
wire   [27:0] grp_fu_403_p2;
wire   [25:0] grp_fu_963_p1;
wire   [26:0] grp_fu_406_p2;
wire   [23:0] p_shl10_fu_1081_p3;
wire   [19:0] p_shl12_fu_1093_p3;
wire  signed [24:0] p_shl14_cast_fu_1101_p1;
wire  signed [24:0] p_shl12_cast_fu_1089_p1;
wire   [24:0] p_Val2_1_fu_1105_p2;
wire   [26:0] p_shl9_fu_1121_p3;
wire   [23:0] p_shl11_fu_1133_p3;
wire  signed [27:0] p_shl11_cast_fu_1141_p1;
wire  signed [27:0] p_shl9_cast_fu_1129_p1;
wire   [27:0] p_Val2_1_2_fu_1145_p2;
wire   [23:0] p_shl7_fu_1171_p3;
wire   [18:0] p_shl8_fu_1183_p3;
wire  signed [24:0] p_shl7_cast_fu_1179_p1;
wire  signed [24:0] p_shl8_cast_fu_1191_p1;
wire   [24:0] p_Val2_1_4_fu_1195_p2;
wire   [24:0] p_shl5_fu_1211_p3;
wire   [22:0] p_shl6_fu_1223_p3;
wire  signed [25:0] p_shl5_cast_fu_1219_p1;
wire  signed [25:0] p_shl6_cast_fu_1231_p1;
wire   [25:0] p_Val2_1_6_fu_1235_p2;
wire   [26:0] grp_fu_407_p2;
wire   [23:0] p_shl4_fu_1265_p3;
wire  signed [24:0] p_shl4_cast_fu_1273_p1;
wire  signed [24:0] OP1_V_10_cast_fu_1261_p1;
wire   [24:0] p_Val2_1_10_fu_1277_p2;
wire   [19:0] p_shl3_fu_1297_p3;
wire  signed [20:0] p_shl3_cast_fu_1305_p1;
wire   [20:0] p_neg_fu_1309_p2;
wire  signed [20:0] OP1_V_12_cast_fu_1293_p1;
wire   [20:0] p_Val2_1_12_fu_1315_p2;
wire   [20:0] p_shl2_fu_1341_p3;
wire  signed [21:0] p_shl2_cast_fu_1349_p1;
wire   [21:0] p_Val2_1_17_fu_1353_p2;
wire   [24:0] p_shl_fu_1389_p3;
wire   [20:0] p_shl1_fu_1401_p3;
wire  signed [25:0] p_shl_cast_fu_1397_p1;
wire  signed [25:0] p_shl1_cast_fu_1409_p1;
wire   [25:0] p_Val2_1_26_fu_1413_p2;
wire   [26:0] tmp_35_fu_1474_p1;
wire   [23:0] tmp_43_fu_1484_p1;
wire   [24:0] tmp_183_fu_1497_p1;
wire   [14:0] tmp_183_fu_1497_p4;
wire   [25:0] tmp_52_fu_1511_p1;
wire  signed [17:0] tmp_6_fu_1444_p1;
wire  signed [17:0] tmp_9_fu_1447_p1;
wire  signed [17:0] tmp_12_fu_1451_p1;
wire   [17:0] tmp19_fu_1527_p2;
wire   [17:0] tmp18_fu_1521_p2;
wire  signed [17:0] tmp_15_fu_1454_p1;
wire  signed [17:0] tmp_18_fu_1457_p1;
wire  signed [17:0] tmp_21_fu_1461_p1;
wire   [17:0] tmp22_fu_1544_p2;
wire   [17:0] tmp21_fu_1538_p2;
wire   [17:0] tmp20_fu_1550_p2;
wire   [17:0] tmp17_fu_1532_p2;
wire  signed [17:0] tmp_24_fu_1464_p1;
wire  signed [17:0] tmp_27_fu_1467_p1;
wire  signed [17:0] tmp_30_fu_1471_p1;
wire  signed [15:0] tmp_47_cast_fu_1494_p1;
wire  signed [15:0] tmp_50_cast_fu_1507_p1;
wire   [25:0] tmp_63_fu_1596_p1;
wire   [23:0] tmp_184_fu_1606_p1;
wire   [13:0] tmp_184_fu_1606_p4;
wire  signed [17:0] tmp_33_fu_1580_p1;
wire  signed [17:0] tmp_36_fu_1583_p1;
wire  signed [17:0] tmp_39_fu_1586_p1;
wire   [17:0] tmp29_fu_1630_p2;
wire   [17:0] tmp28_fu_1624_p2;
wire   [17:0] tmp27_fu_1636_p2;
wire   [17:0] tmp24_fu_1620_p2;
wire  signed [17:0] tmp_44_fu_1593_p1;
wire  signed [17:0] tmp34_cast_fu_1654_p1;
wire   [17:0] tmp33_fu_1648_p2;
wire  signed [15:0] tmp_10_15_cast_fu_1590_p1;
wire   [15:0] tmp45_fu_1663_p2;
wire  signed [15:0] tmp_72_cast_fu_1616_p1;
wire  signed [17:0] tmp_53_fu_1675_p1;
wire  signed [17:0] tmp_56_fu_1678_p1;
wire   [17:0] tmp37_fu_1706_p2;
wire   [17:0] tmp36_fu_1700_p2;
wire  signed [17:0] tmp_58_fu_1682_p1;
wire  signed [17:0] tmp_60_fu_1686_p1;
wire  signed [17:0] tmp_62_fu_1690_p1;
wire   [17:0] tmp41_fu_1723_p2;
wire   [17:0] tmp40_fu_1717_p2;
wire  signed [17:0] tmp_64_fu_1693_p1;
wire  signed [17:0] tmp_66_fu_1696_p1;
wire  signed [17:0] tmp44_cast_fu_1741_p1;
wire   [17:0] tmp43_fu_1735_p2;
wire   [17:0] tmp42_fu_1744_p2;
wire   [17:0] tmp39_fu_1729_p2;
wire   [17:0] tmp31_fu_1760_p2;
wire   [17:0] tmp30_fu_1764_p2;
wire   [17:0] tmp15_fu_1756_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_pipeline_idle_pp0;
reg    ap_pipeline_start_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'b1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_preg = 1'b0;
end

myproject_mul_18sjbC #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 28 ))
myproject_mul_18sjbC_x_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_402_p0),
    .din1(grp_fu_402_p1),
    .ce(1'b1),
    .dout(grp_fu_402_p2)
);

myproject_mul_18sjbC #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 28 ))
myproject_mul_18sjbC_x_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_403_p0),
    .din1(grp_fu_403_p1),
    .ce(1'b1),
    .dout(grp_fu_403_p2)
);

myproject_mul_18sjbC #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 28 ))
myproject_mul_18sjbC_x_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_404_p0),
    .din1(grp_fu_404_p1),
    .ce(1'b1),
    .dout(grp_fu_404_p2)
);

myproject_mul_18sfYi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 27 ))
myproject_mul_18sfYi_x_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_405_p0),
    .din1(grp_fu_405_p1),
    .ce(1'b1),
    .dout(grp_fu_405_p2)
);

myproject_mul_18seOg #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 27 ))
myproject_mul_18seOg_x_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_406_p0),
    .din1(grp_fu_406_p1),
    .ce(1'b1),
    .dout(grp_fu_406_p2)
);

myproject_mul_18seOg #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 27 ))
myproject_mul_18seOg_x_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_407_p0),
    .din1(grp_fu_407_p1),
    .ce(1'b1),
    .dout(grp_fu_407_p2)
);

myproject_mul_18sg8j #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 27 ))
myproject_mul_18sg8j_x_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_408_p0),
    .din1(grp_fu_408_p1),
    .ce(1'b1),
    .dout(grp_fu_408_p2)
);

myproject_mul_18seOg #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 27 ))
myproject_mul_18seOg_x_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_409_p0),
    .din1(grp_fu_409_p1),
    .ce(1'b1),
    .dout(grp_fu_409_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_preg <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
            ap_enable_reg_pp0_iter0_preg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & ~(1'b1 == ap_enable_reg_pp0_iter1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        ap_port_reg_data_0_V_read <= data_0_V_read;
        ap_port_reg_data_11_V_read <= data_11_V_read;
        ap_port_reg_data_13_V_read <= data_13_V_read;
        ap_port_reg_data_14_V_read <= data_14_V_read;
        ap_port_reg_data_15_V_read <= data_15_V_read;
        ap_port_reg_data_16_V_read <= data_16_V_read;
        ap_port_reg_data_17_V_read <= data_17_V_read;
        ap_port_reg_data_18_V_read <= data_18_V_read;
        ap_port_reg_data_19_V_read <= data_19_V_read;
        ap_port_reg_data_20_V_read <= data_20_V_read;
        ap_port_reg_data_21_V_read <= data_21_V_read;
        ap_port_reg_data_22_V_read <= data_22_V_read;
        ap_port_reg_data_23_V_read <= data_23_V_read;
        ap_port_reg_data_24_V_read <= data_24_V_read;
        ap_port_reg_data_25_V_read <= data_25_V_read;
        ap_port_reg_data_26_V_read <= data_26_V_read;
        ap_port_reg_data_27_V_read <= data_27_V_read;
        ap_port_reg_data_28_V_read <= data_28_V_read;
        ap_port_reg_data_29_V_read <= data_29_V_read;
        ap_port_reg_data_2_V_read <= data_2_V_read;
        ap_port_reg_data_30_V_read <= data_30_V_read;
        ap_port_reg_data_31_V_read <= data_31_V_read;
        ap_port_reg_data_4_V_read <= data_4_V_read;
        ap_port_reg_data_6_V_read <= data_6_V_read;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        reg_973 <= {{grp_fu_409_p2[ap_const_lv32_1A : ap_const_lv32_A]}};
        reg_977 <= {{grp_fu_408_p2[ap_const_lv32_1A : ap_const_lv32_A]}};
        reg_985 <= {{grp_fu_404_p2[ap_const_lv32_1B : ap_const_lv32_A]}};
        reg_993 <= {{grp_fu_403_p2[ap_const_lv32_1B : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0))))) begin
        reg_981 <= {{grp_fu_402_p2[ap_const_lv32_1B : ap_const_lv32_A]}};
        reg_989 <= {{grp_fu_405_p2[ap_const_lv32_1A : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1)) | ((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0))))) begin
        reg_997 <= {{grp_fu_963_p1[ap_const_lv32_19 : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        tmp16_reg_1965 <= tmp16_fu_1556_p2;
        tmp25_reg_1970 <= tmp25_fu_1562_p2;
        tmp26_reg_1975 <= tmp26_fu_1568_p2;
        tmp34_reg_1980 <= tmp34_fu_1574_p2;
        tmp_35_reg_1945 <= {{tmp_35_fu_1474_p1[ap_const_lv32_1A : ap_const_lv32_A]}};
        tmp_43_reg_1950 <= {{tmp_43_fu_1484_p1[ap_const_lv32_17 : ap_const_lv32_A]}};
        tmp_52_reg_1955 <= {{tmp_52_fu_1511_p1[ap_const_lv32_19 : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        tmp23_reg_1990 <= tmp23_fu_1642_p2;
        tmp32_reg_1995 <= tmp32_fu_1657_p2;
        tmp44_reg_2000 <= tmp44_fu_1669_p2;
        tmp_63_reg_1985 <= {{tmp_63_fu_1596_p1[ap_const_lv32_19 : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
        tmp35_reg_2005 <= tmp35_fu_1711_p2;
        tmp38_reg_2010 <= tmp38_fu_1750_p2;
        tmp_10_2_reg_1860 <= {{p_Val2_1_2_fu_1145_p2[ap_const_lv32_1B : ap_const_lv32_A]}};
        tmp_11_reg_1865 <= {{grp_fu_406_p2[ap_const_lv32_1A : ap_const_lv32_A]}};
        tmp_14_reg_1870 <= {{p_Val2_1_4_fu_1195_p2[ap_const_lv32_18 : ap_const_lv32_A]}};
        tmp_182_reg_1900 <= {{p_Val2_1_17_fu_1353_p2[ap_const_lv32_15 : ap_const_lv32_A]}};
        tmp_20_reg_1875 <= {{p_Val2_1_6_fu_1235_p2[ap_const_lv32_19 : ap_const_lv32_A]}};
        tmp_23_reg_1880 <= {{grp_fu_407_p2[ap_const_lv32_1A : ap_const_lv32_A]}};
        tmp_29_reg_1885 <= {{p_Val2_1_10_fu_1277_p2[ap_const_lv32_18 : ap_const_lv32_A]}};
        tmp_32_reg_1890 <= {{p_Val2_1_12_fu_1315_p2[ap_const_lv32_14 : ap_const_lv32_A]}};
        tmp_41_reg_1895 <= {{ap_port_reg_data_16_V_read[ap_const_lv32_11 : ap_const_lv32_3]}};
        tmp_5_reg_1855 <= {{p_Val2_1_fu_1105_p2[ap_const_lv32_18 : ap_const_lv32_A]}};
        tmp_61_reg_1925 <= {{p_Val2_1_26_fu_1413_p2[ap_const_lv32_19 : ap_const_lv32_A]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        tmp_10_3_reg_1960 <= {{grp_fu_403_p2[ap_const_lv32_1B : ap_const_lv32_A]}};
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_enable_reg_pp0_iter2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_pipeline_idle_pp0 = 1'b1;
    end else begin
        ap_pipeline_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_start))) begin
        ap_pipeline_start_pp0 = 1'b1;
    end else begin
        ap_pipeline_start_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_402_p0 = OP1_V_28_cast_fu_1429_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_402_p0 = OP1_V_17_cast_fu_1056_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_402_p0 = OP1_V_7_cast_fu_1016_p1;
        end else begin
            grp_fu_402_p0 = 'bx;
        end
    end else begin
        grp_fu_402_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_402_p1 = ap_const_lv26_3FFFF97;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_402_p1 = ap_const_lv28_FFFFE4A;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_402_p1 = ap_const_lv28_FFFFE92;
        end else begin
            grp_fu_402_p1 = 'bx;
        end
    end else begin
        grp_fu_402_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_403_p0 = OP1_V_23_cast_fu_1369_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_403_p0 = OP1_V_22_cast_fu_1076_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_403_p0 = OP1_V_11_cast_fu_1036_p1;
        end else begin
            grp_fu_403_p0 = 'bx;
        end
    end else begin
        grp_fu_403_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_403_p1 = ap_const_lv28_FFFFEB6;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_403_p1 = ap_const_lv28_FFFFED4;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_403_p1 = ap_const_lv28_FFFFE73;
        end else begin
            grp_fu_403_p1 = 'bx;
        end
    end else begin
        grp_fu_403_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_404_p0 = OP1_V_24_cast_fu_1374_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_404_p0 = OP1_V_13_cast_fu_1041_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_404_p0 = OP1_V_9_cast_fu_1026_p1;
        end else begin
            grp_fu_404_p0 = 'bx;
        end
    end else begin
        grp_fu_404_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_404_p1 = ap_const_lv28_FFFFE87;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_404_p1 = ap_const_lv27_7FFFF5C;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_404_p1 = ap_const_lv28_FFFFEB3;
        end else begin
            grp_fu_404_p1 = 'bx;
        end
    end else begin
        grp_fu_404_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_405_p0 = OP1_V_21_cast_fu_1071_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_405_p0 = OP1_V_cast_fu_1031_p1;
        end else begin
            grp_fu_405_p0 = 'bx;
        end
    end else begin
        grp_fu_405_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_405_p1 = ap_const_lv27_7FFFF0B;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_405_p1 = ap_const_lv27_F2;
        end else begin
            grp_fu_405_p1 = 'bx;
        end
    end else begin
        grp_fu_405_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_406_p0 = OP1_V_25_cast_fu_1379_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_406_p0 = OP1_V_14_cast_fu_1046_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_406_p0 = OP1_V_3_cast_fu_1006_p1;
        end else begin
            grp_fu_406_p0 = 'bx;
        end
    end else begin
        grp_fu_406_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_406_p1 = ap_const_lv26_4A;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_406_p1 = ap_const_lv26_5C;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_406_p1 = ap_const_lv27_7FFFF4B;
        end else begin
            grp_fu_406_p1 = 'bx;
        end
    end else begin
        grp_fu_406_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_407_p0 = OP1_V_30_cast_fu_1439_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_407_p0 = OP1_V_19_cast_fu_1061_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_407_p0 = OP1_V_8_cast_fu_1021_p1;
        end else begin
            grp_fu_407_p0 = 'bx;
        end
    end else begin
        grp_fu_407_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_407_p1 = ap_const_lv24_1D;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_407_p1 = ap_const_lv25_32;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_407_p1 = ap_const_lv27_7FFFF52;
        end else begin
            grp_fu_407_p1 = 'bx;
        end
    end else begin
        grp_fu_407_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_408_p0 = OP1_V_26_cast_fu_1384_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_408_p0 = OP1_V_16_cast_fu_1051_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_408_p0 = OP1_V_5_cast_fu_1011_p1;
        end else begin
            grp_fu_408_p0 = 'bx;
        end
    end else begin
        grp_fu_408_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_408_p1 = ap_const_lv27_9F;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_408_p1 = ap_const_lv24_19;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_408_p1 = ap_const_lv27_BF;
        end else begin
            grp_fu_408_p1 = 'bx;
        end
    end else begin
        grp_fu_408_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_409_p0 = OP1_V_29_cast_fu_1434_p1;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_409_p0 = OP1_V_20_cast_fu_1066_p1;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_409_p0 = OP1_V_1_cast_fu_1001_p1;
        end else begin
            grp_fu_409_p0 = 'bx;
        end
    end else begin
        grp_fu_409_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            grp_fu_409_p1 = ap_const_lv27_7FFFF46;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            grp_fu_409_p1 = ap_const_lv26_3FFFF9F;
        end else if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            grp_fu_409_p1 = ap_const_lv27_7FFFF71;
        end else begin
            grp_fu_409_p1 = 'bx;
        end
    end else begin
        grp_fu_409_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & ~(1'b1 == ap_pipeline_idle_pp0) & ~(~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_pipeline_start_pp0)) & ~((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_pipeline_idle_pp0)) | (~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & (1'b1 == ap_pipeline_start_pp0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage2;
        end
        ap_ST_fsm_pp0_stage2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP1_V_10_cast_fu_1261_p1 = $signed(ap_port_reg_data_11_V_read);

assign OP1_V_11_cast_fu_1036_p1 = $signed(data_12_V_read);

assign OP1_V_12_cast_fu_1293_p1 = $signed(ap_port_reg_data_13_V_read);

assign OP1_V_13_cast_fu_1041_p1 = $signed(ap_port_reg_data_14_V_read);

assign OP1_V_14_cast_fu_1046_p1 = $signed(ap_port_reg_data_15_V_read);

assign OP1_V_16_cast_fu_1051_p1 = $signed(ap_port_reg_data_17_V_read);

assign OP1_V_17_cast_fu_1056_p1 = $signed(ap_port_reg_data_18_V_read);

assign OP1_V_19_cast_fu_1061_p1 = $signed(ap_port_reg_data_20_V_read);

assign OP1_V_1_cast_fu_1001_p1 = $signed(data_1_V_read);

assign OP1_V_20_cast_fu_1066_p1 = $signed(ap_port_reg_data_21_V_read);

assign OP1_V_21_cast_fu_1071_p1 = $signed(ap_port_reg_data_22_V_read);

assign OP1_V_22_cast_fu_1076_p1 = $signed(ap_port_reg_data_23_V_read);

assign OP1_V_23_cast_fu_1369_p1 = $signed(ap_port_reg_data_24_V_read);

assign OP1_V_24_cast_fu_1374_p1 = $signed(ap_port_reg_data_25_V_read);

assign OP1_V_25_cast_fu_1379_p1 = $signed(ap_port_reg_data_26_V_read);

assign OP1_V_26_cast_fu_1384_p1 = $signed(ap_port_reg_data_27_V_read);

assign OP1_V_28_cast_fu_1429_p1 = $signed(ap_port_reg_data_29_V_read);

assign OP1_V_29_cast_fu_1434_p1 = $signed(ap_port_reg_data_30_V_read);

assign OP1_V_30_cast_fu_1439_p1 = $signed(ap_port_reg_data_31_V_read);

assign OP1_V_3_cast_fu_1006_p1 = $signed(data_3_V_read);

assign OP1_V_5_cast_fu_1011_p1 = $signed(data_5_V_read);

assign OP1_V_7_cast_fu_1016_p1 = $signed(data_7_V_read);

assign OP1_V_8_cast_fu_1021_p1 = $signed(data_8_V_read);

assign OP1_V_9_cast_fu_1026_p1 = $signed(data_9_V_read);

assign OP1_V_cast_fu_1031_p1 = $signed(data_10_V_read);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[ap_const_lv32_2];

assign ap_return = (tmp30_fu_1764_p2 + tmp15_fu_1756_p2);

assign grp_fu_963_p1 = grp_fu_406_p2;

assign p_Val2_1_10_fu_1277_p2 = ($signed(p_shl4_cast_fu_1273_p1) + $signed(OP1_V_10_cast_fu_1261_p1));

assign p_Val2_1_12_fu_1315_p2 = ($signed(p_neg_fu_1309_p2) - $signed(OP1_V_12_cast_fu_1293_p1));

assign p_Val2_1_17_fu_1353_p2 = ($signed(ap_const_lv22_0) - $signed(p_shl2_cast_fu_1349_p1));

assign p_Val2_1_26_fu_1413_p2 = ($signed(p_shl_cast_fu_1397_p1) - $signed(p_shl1_cast_fu_1409_p1));

assign p_Val2_1_2_fu_1145_p2 = ($signed(p_shl11_cast_fu_1141_p1) - $signed(p_shl9_cast_fu_1129_p1));

assign p_Val2_1_4_fu_1195_p2 = ($signed(p_shl7_cast_fu_1179_p1) + $signed(p_shl8_cast_fu_1191_p1));

assign p_Val2_1_6_fu_1235_p2 = ($signed(p_shl5_cast_fu_1219_p1) + $signed(p_shl6_cast_fu_1231_p1));

assign p_Val2_1_fu_1105_p2 = ($signed(p_shl14_cast_fu_1101_p1) - $signed(p_shl12_cast_fu_1089_p1));

assign p_neg_fu_1309_p2 = ($signed(ap_const_lv21_0) - $signed(p_shl3_cast_fu_1305_p1));

assign p_shl10_fu_1081_p3 = {{ap_port_reg_data_0_V_read}, {ap_const_lv6_0}};

assign p_shl11_cast_fu_1141_p1 = $signed(p_shl11_fu_1133_p3);

assign p_shl11_fu_1133_p3 = {{ap_port_reg_data_2_V_read}, {ap_const_lv6_0}};

assign p_shl12_cast_fu_1089_p1 = $signed(p_shl10_fu_1081_p3);

assign p_shl12_fu_1093_p3 = {{ap_port_reg_data_0_V_read}, {ap_const_lv2_0}};

assign p_shl14_cast_fu_1101_p1 = $signed(p_shl12_fu_1093_p3);

assign p_shl1_cast_fu_1409_p1 = $signed(p_shl1_fu_1401_p3);

assign p_shl1_fu_1401_p3 = {{ap_port_reg_data_28_V_read}, {ap_const_lv3_0}};

assign p_shl2_cast_fu_1349_p1 = $signed(p_shl2_fu_1341_p3);

assign p_shl2_fu_1341_p3 = {{ap_port_reg_data_19_V_read}, {ap_const_lv3_0}};

assign p_shl3_cast_fu_1305_p1 = $signed(p_shl3_fu_1297_p3);

assign p_shl3_fu_1297_p3 = {{ap_port_reg_data_13_V_read}, {ap_const_lv2_0}};

assign p_shl4_cast_fu_1273_p1 = $signed(p_shl4_fu_1265_p3);

assign p_shl4_fu_1265_p3 = {{ap_port_reg_data_11_V_read}, {ap_const_lv6_0}};

assign p_shl5_cast_fu_1219_p1 = $signed(p_shl5_fu_1211_p3);

assign p_shl5_fu_1211_p3 = {{ap_port_reg_data_6_V_read}, {ap_const_lv7_0}};

assign p_shl6_cast_fu_1231_p1 = $signed(p_shl6_fu_1223_p3);

assign p_shl6_fu_1223_p3 = {{ap_port_reg_data_6_V_read}, {ap_const_lv5_0}};

assign p_shl7_cast_fu_1179_p1 = $signed(p_shl7_fu_1171_p3);

assign p_shl7_fu_1171_p3 = {{ap_port_reg_data_4_V_read}, {ap_const_lv6_0}};

assign p_shl8_cast_fu_1191_p1 = $signed(p_shl8_fu_1183_p3);

assign p_shl8_fu_1183_p3 = {{ap_port_reg_data_4_V_read}, {1'b0}};

assign p_shl9_cast_fu_1129_p1 = $signed(p_shl9_fu_1121_p3);

assign p_shl9_fu_1121_p3 = {{ap_port_reg_data_2_V_read}, {ap_const_lv9_0}};

assign p_shl_cast_fu_1397_p1 = $signed(p_shl_fu_1389_p3);

assign p_shl_fu_1389_p3 = {{ap_port_reg_data_28_V_read}, {ap_const_lv7_0}};

assign tmp15_fu_1756_p2 = (tmp23_reg_1990 + tmp16_reg_1965);

assign tmp16_fu_1556_p2 = (tmp20_fu_1550_p2 + tmp17_fu_1532_p2);

assign tmp17_fu_1532_p2 = (tmp19_fu_1527_p2 + tmp18_fu_1521_p2);

assign tmp18_fu_1521_p2 = ($signed(tmp_6_fu_1444_p1) + $signed(tmp_9_fu_1447_p1));

assign tmp19_fu_1527_p2 = ($signed(tmp_10_2_reg_1860) + $signed(tmp_12_fu_1451_p1));

assign tmp20_fu_1550_p2 = (tmp22_fu_1544_p2 + tmp21_fu_1538_p2);

assign tmp21_fu_1538_p2 = ($signed(tmp_15_fu_1454_p1) + $signed(tmp_18_fu_1457_p1));

assign tmp22_fu_1544_p2 = ($signed(tmp_21_fu_1461_p1) + $signed(reg_981));

assign tmp23_fu_1642_p2 = (tmp27_fu_1636_p2 + tmp24_fu_1620_p2);

assign tmp24_fu_1620_p2 = (tmp26_reg_1975 + tmp25_reg_1970);

assign tmp25_fu_1562_p2 = ($signed(tmp_24_fu_1464_p1) + $signed(reg_985));

assign tmp26_fu_1568_p2 = ($signed(tmp_27_fu_1467_p1) + $signed(tmp_30_fu_1471_p1));

assign tmp27_fu_1636_p2 = (tmp29_fu_1630_p2 + tmp28_fu_1624_p2);

assign tmp28_fu_1624_p2 = ($signed(reg_993) + $signed(tmp_33_fu_1580_p1));

assign tmp29_fu_1630_p2 = ($signed(tmp_36_fu_1583_p1) + $signed(tmp_39_fu_1586_p1));

assign tmp30_fu_1764_p2 = (tmp38_reg_2010 + tmp31_fu_1760_p2);

assign tmp31_fu_1760_p2 = (tmp35_reg_2005 + tmp32_reg_1995);

assign tmp32_fu_1657_p2 = ($signed(tmp34_cast_fu_1654_p1) + $signed(tmp33_fu_1648_p2));

assign tmp33_fu_1648_p2 = ($signed(tmp_44_fu_1593_p1) + $signed(reg_981));

assign tmp34_cast_fu_1654_p1 = $signed(tmp34_reg_1980);

assign tmp34_fu_1574_p2 = ($signed(tmp_47_cast_fu_1494_p1) + $signed(tmp_50_cast_fu_1507_p1));

assign tmp35_fu_1711_p2 = (tmp37_fu_1706_p2 + tmp36_fu_1700_p2);

assign tmp36_fu_1700_p2 = ($signed(tmp_53_fu_1675_p1) + $signed(tmp_56_fu_1678_p1));

assign tmp37_fu_1706_p2 = (tmp_10_3_reg_1960 + reg_993);

assign tmp38_fu_1750_p2 = (tmp42_fu_1744_p2 + tmp39_fu_1729_p2);

assign tmp39_fu_1729_p2 = (tmp41_fu_1723_p2 + tmp40_fu_1717_p2);

assign tmp40_fu_1717_p2 = ($signed(reg_985) + $signed(tmp_58_fu_1682_p1));

assign tmp41_fu_1723_p2 = ($signed(tmp_60_fu_1686_p1) + $signed(tmp_62_fu_1690_p1));

assign tmp42_fu_1744_p2 = ($signed(tmp44_cast_fu_1741_p1) + $signed(tmp43_fu_1735_p2));

assign tmp43_fu_1735_p2 = ($signed(tmp_64_fu_1693_p1) + $signed(tmp_66_fu_1696_p1));

assign tmp44_cast_fu_1741_p1 = $signed(tmp44_reg_2000);

assign tmp44_fu_1669_p2 = ($signed(tmp45_fu_1663_p2) + $signed(tmp_72_cast_fu_1616_p1));

assign tmp45_fu_1663_p2 = ($signed(tmp_10_15_cast_fu_1590_p1) + $signed(ap_const_lv16_FF86));

assign tmp_10_15_cast_fu_1590_p1 = $signed(tmp_41_reg_1895);

assign tmp_12_fu_1451_p1 = $signed(tmp_11_reg_1865);

assign tmp_15_fu_1454_p1 = $signed(tmp_14_reg_1870);

assign tmp_183_fu_1497_p1 = grp_fu_407_p2;

assign tmp_183_fu_1497_p4 = {{tmp_183_fu_1497_p1[ap_const_lv32_18 : ap_const_lv32_A]}};

assign tmp_184_fu_1606_p1 = grp_fu_407_p2;

assign tmp_184_fu_1606_p4 = {{tmp_184_fu_1606_p1[ap_const_lv32_17 : ap_const_lv32_A]}};

assign tmp_18_fu_1457_p1 = $signed(reg_977);

assign tmp_21_fu_1461_p1 = $signed(tmp_20_reg_1875);

assign tmp_24_fu_1464_p1 = $signed(tmp_23_reg_1880);

assign tmp_27_fu_1467_p1 = $signed(reg_989);

assign tmp_30_fu_1471_p1 = $signed(tmp_29_reg_1885);

assign tmp_33_fu_1580_p1 = $signed(tmp_32_reg_1890);

assign tmp_35_fu_1474_p1 = grp_fu_404_p2;

assign tmp_36_fu_1583_p1 = $signed(tmp_35_reg_1945);

assign tmp_39_fu_1586_p1 = $signed(reg_997);

assign tmp_43_fu_1484_p1 = grp_fu_408_p2;

assign tmp_44_fu_1593_p1 = $signed(tmp_43_reg_1950);

assign tmp_47_cast_fu_1494_p1 = $signed(tmp_182_reg_1900);

assign tmp_50_cast_fu_1507_p1 = $signed(tmp_183_fu_1497_p4);

assign tmp_52_fu_1511_p1 = grp_fu_409_p2;

assign tmp_53_fu_1675_p1 = $signed(tmp_52_reg_1955);

assign tmp_56_fu_1678_p1 = $signed(reg_989);

assign tmp_58_fu_1682_p1 = $signed(reg_997);

assign tmp_60_fu_1686_p1 = $signed(reg_977);

assign tmp_62_fu_1690_p1 = $signed(tmp_61_reg_1925);

assign tmp_63_fu_1596_p1 = grp_fu_402_p2;

assign tmp_64_fu_1693_p1 = $signed(tmp_63_reg_1985);

assign tmp_66_fu_1696_p1 = $signed(reg_973);

assign tmp_6_fu_1444_p1 = $signed(tmp_5_reg_1855);

assign tmp_72_cast_fu_1616_p1 = $signed(tmp_184_fu_1606_p4);

assign tmp_9_fu_1447_p1 = $signed(reg_973);

endmodule //compute_layer_0_0
